
var TWASMModule = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(TWASMModule) {
  TWASMModule = TWASMModule || {};


var g;g||(g=typeof TWASMModule !== 'undefined' ? TWASMModule : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});var ca={},t;for(t in g)g.hasOwnProperty(t)&&(ca[t]=g[t]);var da=[],ea="./this.program";function fa(a,b){throw b;}var v="";"undefined"!==typeof document&&document.currentScript&&(v=document.currentScript.src);_scriptDir&&(v=_scriptDir);0!==v.indexOf("blob:")?v=v.substr(0,v.lastIndexOf("/")+1):v="";var x=g.print||console.log.bind(console),y=g.printErr||console.warn.bind(console);
for(t in ca)ca.hasOwnProperty(t)&&(g[t]=ca[t]);ca=null;g.arguments&&(da=g.arguments);g.thisProgram&&(ea=g.thisProgram);g.quit&&(fa=g.quit);function ha(a){ia||(ia={});ia[a]||(ia[a]=1,y(a))}var ia,ja;g.wasmBinary&&(ja=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!==typeof WebAssembly&&ka("no native wasm support detected");var la,A=!1,ma;function na(a,b){a||ka("Assertion failed: "+b)}
function oa(a,b){b=1==b?pa(a.length):qa(a.length);a.subarray||a.slice?B.set(a,b):B.set(new Uint8Array(a),b);return b}var ra="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function sa(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ra)return ra.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function C(a,b){return a?sa(B,a,b):""}
function ta(a,b,c,d){if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var l=a.charCodeAt(f);if(55296<=l&&57343>=l){var k=a.charCodeAt(++f);l=65536+((l&1023)<<10)|k&1023}if(127>=l){if(c>=d)break;b[c++]=l}else{if(2047>=l){if(c+1>=d)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=d)break;b[c++]=224|l>>12}else{if(c+3>=d)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-e}
function ua(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}var va="undefined"!==typeof TextDecoder?new TextDecoder("utf-16le"):void 0;function wa(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&xa[c];)++c;c<<=1;if(32<c-a&&va)return va.decode(B.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=D[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}
function ya(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d}function za(a){return 2*a.length}function Aa(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}
function Ba(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}function Ca(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Da(a){var b=ua(a)+1,c=pa(b);ta(a,F,c,b);return c}var Ea,F,B,D,xa,E,G,Fa,Ga;
function Ha(){var a=la.buffer;Ea=a;g.HEAP8=F=new Int8Array(a);g.HEAP16=D=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=B=new Uint8Array(a);g.HEAPU16=xa=new Uint16Array(a);g.HEAPU32=G=new Uint32Array(a);g.HEAPF32=Fa=new Float32Array(a);g.HEAPF64=Ga=new Float64Array(a)}var H,Ia=[],Ja=[],Ka=[],La=[];function Ma(){var a=g.preRun.shift();Ia.unshift(a)}var I=0,Na=null,Oa=null;g.preloadedImages={};g.preloadedAudios={};
function ka(a){if(g.onAbort)g.onAbort(a);y(a);A=!0;ma=1;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function Pa(){return J.startsWith("data:application/octet-stream;base64,")}var J;J="thing.wasm.wasm";if(!Pa()){var Qa=J;J=g.locateFile?g.locateFile(Qa,v):v+Qa}function Ra(){var a=J;try{if(a==J&&ja)return new Uint8Array(ja);throw"both async and sync fetching of the wasm failed";}catch(b){ka(b)}}
function Sa(){return ja||"function"!==typeof fetch?Promise.resolve().then(function(){return Ra()}):fetch(J,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+J+"'";return a.arrayBuffer()}).catch(function(){return Ra()})}
var Ua={32584:function(){var a="undefined"!==typeof g?g:"undefined"!==typeof TWASMModule?TWASMModule:null;a&&(a=a.Helper,a.createStringFromStack=function(b){return oa(Ta(b),1)},a.createStringFromHeap=function(b){return oa(Ta(b),0)},a.freeString=function(b){return K(b)},a.utf8ToString=function(b){return C(b)})},33109:function(){function a(b){try{return decodeURIComponent(escape(b))}catch(c){return String.fromCharCode(65533)}}window.decodeBufferToString=function(b){var c=b.length,d="",e="";c=Math.min(b.length,
c||Infinity);for(var f=0;f<c;f++)127>=b[f]?(d+=a(e)+String.fromCharCode(b[f]),e=""):e+="%"+b[f].toString(16);return d+a(e)}},33684:function(a,b){a=C(a);b=C(b);window[a]&&delete window[a][b]}};function Va(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(g);else{var c=b.Fa;"number"===typeof c?void 0===b.va?H.get(c)():H.get(c)(b.va):c(void 0===b.va?null:b.va)}}}function Wa(a){a instanceof Xa||"unwind"==a||(y("exception thrown: "+a),fa(1,a))}var Ya={};
function Za(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function $a(a){return this.fromWireType(G[a>>2])}var M={},N={},ab={};function bb(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function cb(a,b){a=bb(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function db(a){var b=Error,c=cb(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var eb=void 0;function fb(a){throw new eb(a);}
function O(a,b,c){function d(k){k=c(k);k.length!==a.length&&fb("Mismatched type converter count");for(var m=0;m<a.length;++m)P(a[m],k[m])}a.forEach(function(k){ab[k]=b});var e=Array(b.length),f=[],l=0;b.forEach(function(k,m){N.hasOwnProperty(k)?e[m]=N[k]:(f.push(k),M.hasOwnProperty(k)||(M[k]=[]),M[k].push(function(){e[m]=N[k];++l;l===f.length&&d(e)}))});0===f.length&&d(e)}
function gb(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var hb=void 0;function Q(a){for(var b="";B[a];)b+=hb[B[a++]];return b}var ib=void 0;function R(a){throw new ib(a);}
function P(a,b,c){c=c||{};if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||R('type "'+d+'" must have a positive integer typeid pointer');if(N.hasOwnProperty(a)){if(c.cb)return;R("Cannot register type '"+d+"' twice")}N[a]=b;delete ab[a];M.hasOwnProperty(a)&&(b=M[a],delete M[a],b.forEach(function(e){e()}))}function jb(a){R(a.ka.na.la.name+" instance already deleted")}var kb=!1;function lb(){}
function mb(a){--a.count.value;0===a.count.value&&(a.qa?a.sa.ua(a.qa):a.na.la.ua(a.ma))}function nb(a){if("undefined"===typeof FinalizationGroup)return nb=function(b){return b},a;kb=new FinalizationGroup(function(b){for(var c=b.next();!c.done;c=b.next())c=c.value,c.ma?mb(c):console.warn("object already deleted: "+c.ma)});nb=function(b){kb.register(b,b.ka,b.ka);return b};lb=function(b){kb.unregister(b.ka)};return nb(a)}var ob=void 0,pb=[];
function qb(){for(;pb.length;){var a=pb.pop();a.ka.ya=!1;a["delete"]()}}function S(){}var rb={};function sb(a,b,c){if(void 0===a[b].oa){var d=a[b];a[b]=function(){a[b].oa.hasOwnProperty(arguments.length)||R("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].oa+")!");return a[b].oa[arguments.length].apply(this,arguments)};a[b].oa=[];a[b].oa[d.xa]=d}}
function tb(a,b){g.hasOwnProperty(a)?(R("Cannot register public name '"+a+"' twice"),sb(g,a,a),g.hasOwnProperty(void 0)&&R("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),g[a].oa[void 0]=b):g[a]=b}function ub(a,b,c,d,e,f,l,k){this.name=a;this.constructor=b;this.za=c;this.ua=d;this.ta=e;this.Xa=f;this.Da=l;this.Va=k;this.gb=[]}
function vb(a,b,c){for(;b!==c;)b.Da||R("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Da(a),b=b.ta;return a}function wb(a,b){if(null===b)return this.La&&R("null is not a valid "+this.name),0;b.ka||R('Cannot pass "'+xb(b)+'" as a '+this.name);b.ka.ma||R("Cannot pass deleted object as a pointer of type "+this.name);return vb(b.ka.ma,b.ka.na.la,this.la)}
function yb(a,b){if(null===b){this.La&&R("null is not a valid "+this.name);if(this.Ha){var c=this.Ma();null!==a&&a.push(this.ua,c);return c}return 0}b.ka||R('Cannot pass "'+xb(b)+'" as a '+this.name);b.ka.ma||R("Cannot pass deleted object as a pointer of type "+this.name);!this.Ga&&b.ka.na.Ga&&R("Cannot convert argument of type "+(b.ka.sa?b.ka.sa.name:b.ka.na.name)+" to parameter type "+this.name);c=vb(b.ka.ma,b.ka.na.la,this.la);if(this.Ha)switch(void 0===b.ka.qa&&R("Passing raw pointer to smart pointer is illegal"),
this.mb){case 0:b.ka.sa===this?c=b.ka.qa:R("Cannot convert argument of type "+(b.ka.sa?b.ka.sa.name:b.ka.na.name)+" to parameter type "+this.name);break;case 1:c=b.ka.qa;break;case 2:if(b.ka.sa===this)c=b.ka.qa;else{var d=b.clone();c=this.ib(c,U(function(){d["delete"]()}));null!==a&&a.push(this.ua,c)}break;default:R("Unsupporting sharing policy")}return c}
function zb(a,b){if(null===b)return this.La&&R("null is not a valid "+this.name),0;b.ka||R('Cannot pass "'+xb(b)+'" as a '+this.name);b.ka.ma||R("Cannot pass deleted object as a pointer of type "+this.name);b.ka.na.Ga&&R("Cannot convert argument of type "+b.ka.na.name+" to parameter type "+this.name);return vb(b.ka.ma,b.ka.na.la,this.la)}function Ab(a,b,c){if(b===c)return a;if(void 0===c.ta)return null;a=Ab(a,b,c.ta);return null===a?null:c.Va(a)}var Bb={};
function Cb(a,b){for(void 0===b&&R("ptr should not be undefined");a.ta;)b=a.Da(b),a=a.ta;return Bb[b]}function Db(a,b){b.na&&b.ma||fb("makeClassHandle requires ptr and ptrType");!!b.sa!==!!b.qa&&fb("Both smartPtrType and smartPtr must be specified");b.count={value:1};return nb(Object.create(a,{ka:{value:b}}))}
function V(a,b,c,d){this.name=a;this.la=b;this.La=c;this.Ga=d;this.Ha=!1;this.ua=this.ib=this.Ma=this.Ta=this.mb=this.fb=void 0;void 0!==b.ta?this.toWireType=yb:(this.toWireType=d?wb:zb,this.ra=null)}function Eb(a,b){g.hasOwnProperty(a)||fb("Replacing nonexistant public symbol");g[a]=b;g[a].xa=void 0}
function Fb(a,b){var c=[];return function(){c.length=arguments.length;for(var d=0;d<arguments.length;d++)c[d]=arguments[d];a.includes("j")?(d=g["dynCall_"+a],d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)):d=H.get(b).apply(null,c);return d}}function W(a,b){a=Q(a);var c=a.includes("j")?Fb(a,b):H.get(b);"function"!==typeof c&&R("unknown function pointer with signature "+a+": "+b);return c}var Gb=void 0;function Hb(a){a=Ib(a);var b=Q(a);K(a);return b}
function Jb(a,b){function c(f){e[f]||N[f]||(ab[f]?ab[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Gb(a+": "+d.map(Hb).join([", "]));}function Kb(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=cb(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function Lb(a,b,c,d,e){var f=b.length;2>f&&R("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].ra){k=!0;break}var m="void"!==b[0].name,n="",p="";for(c=0;c<f-2;++c)n+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+bb(a)+"("+n+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var r=k?"destructors":"null";n="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[R,d,e,Za,b[0],b[1]];l&&(a+="var thisWired = classParam.toWireType("+r+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+r+", arg"+c+"); // "+b[c+2].name+"\n",n.push("argType"+c),d.push(b[c+2]);l&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(m?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=l?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].ra&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",n.push(f+"_dtor"),d.push(b[c].ra));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");n.push(a+"}\n");return Kb(n).apply(null,d)}function Mb(a,b){for(var c=[],d=0;d<a;d++)c.push(E[(b>>2)+d]);return c}var Nb=[],X=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function Ob(a){4<a&&0===--X[a].Na&&(X[a]=void 0,Nb.push(a))}
function U(a){switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=Nb.length?Nb.pop():X.length;X[b]={Na:1,value:a};return b}}function Pb(a,b,c){switch(b){case 0:return function(d){return this.fromWireType((c?F:B)[d])};case 1:return function(d){return this.fromWireType((c?D:xa)[d>>1])};case 2:return function(d){return this.fromWireType((c?E:G)[d>>2])};default:throw new TypeError("Unknown integer type: "+a);}}
function Qb(a,b){var c=N[a];void 0===c&&R(b+" has unknown type "+Hb(a));return c}function xb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}function Rb(a,b){switch(b){case 2:return function(c){return this.fromWireType(Fa[c>>2])};case 3:return function(c){return this.fromWireType(Ga[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Sb(a,b,c){switch(b){case 0:return c?function(d){return F[d]}:function(d){return B[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return xa[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return G[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}function Y(a){a||R("Cannot use deleted val. handle = "+a);return X[a].value}function Tb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Qb(E[(b>>2)+d],"parameter "+d);return c}var Ub={};
function Vb(a){var b=Ub[a];return void 0===b?Q(a):b}var Wb=[];function Xb(){return"object"===typeof globalThis?globalThis:Function("return this")()}function Yb(a){var b=Wb.length;Wb.push(a);return b}var Zb={},$b=[];
function ac(a,b){bc=a;cc=b;if(dc)if(ec||(ec=!0),0==a)Z=function(){var d=Math.max(0,fc+b-gc())|0;setTimeout(hc,d)};else if(1==a)Z=function(){ic(hc)};else if(2==a){if("undefined"===typeof setImmediate){var c=[];addEventListener("message",function(d){if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}Z=function(){setImmediate(hc)}}}var gc;gc=function(){return performance.now()};
function jc(a,b,c,d,e){function f(){if(l<kc){if(!noExitRuntime)try{lc(ma)}catch(k){Wa(k)}return!1}return!0}na(!dc,"emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");dc=a;mc=d;var l=kc;ec=!1;hc=function(){if(!A)if(0<nc.length){var k=Date.now(),m=nc.shift();m.Fa(m.va);if(oc){var n=oc,p=0==n%1?n-1:Math.floor(n);oc=m.tb?p:(8*n+(p+.5))/9}x('main loop blocker "'+m.name+
'" took '+(Date.now()-k)+" ms");g.setStatus&&(k=g.statusMessage||"Please wait...",m=oc,n=pc.vb,m?m<n?g.setStatus(k+" ("+(n-m)+"/"+n+")"):g.setStatus(k):g.setStatus(""));f()&&setTimeout(hc,0)}else f()&&(qc=qc+1|0,1==bc&&1<cc&&0!=qc%cc?Z():(0==bc&&(fc=gc()),A||g.preMainLoop&&!1===g.preMainLoop()||(rc(a),g.postMainLoop&&g.postMainLoop()),f()&&("object"===typeof SDL&&SDL.audio&&SDL.audio.hb&&SDL.audio.hb(),Z())))};e||(b&&0<b?ac(0,1E3/b):ac(1,1),Z());if(c)throw"unwind";}
function rc(a){if(!A)try{a()}catch(b){Wa(b)}}function sc(a){setTimeout(function(){rc(a)},1E4)}var ec=!1,Z=null,kc=0,dc=null,mc=0,bc=0,cc=0,qc=0,nc=[];function tc(){kc++;var a=bc,b=cc,c=dc;dc=null;jc(c,0,!1,mc,!0);ac(a,b);Z()}var pc={},fc,hc,oc,uc=!1,xc=!1,yc=[],zc=[];
function Ac(){function a(){xc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!Bc){Bc=!0;try{Cc=!0}catch(c){Cc=!1,x("warning: no blob constructor, cannot create blobs with mimetypes")}Dc="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Cc?null:x("warning: no BlobBuilder");Ec="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;g.Sa||"undefined"!==typeof Ec||(x("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.Sa=!0);g.preloadPlugins.push({canHandle:function(c){return!g.Sa&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var l=null;if(Cc)try{l=new Blob([c],{type:Fc(d)}),l.size!==c.length&&(l=new Blob([(new Uint8Array(c)).buffer],{type:Fc(d)}))}catch(n){ha("Blob constructor present but fails: "+
n+"; falling back to blob builder")}l||(l=new Dc,l.append((new Uint8Array(c)).buffer),l=l.getBlob());var k=Ec.createObjectURL(l),m=new Image;m.onload=function(){na(m.complete,"Image "+d+" could not be decoded");var n=document.createElement("canvas");n.width=m.width;n.height=m.height;n.getContext("2d").drawImage(m,0,0);g.preloadedImages[d]=n;Ec.revokeObjectURL(k);e&&e(c)};m.onerror=function(){x("Image "+k+" could not be decoded");f&&f()};m.src=k}});g.preloadPlugins.push({canHandle:function(c){return!g.yb&&
c.substr(-4)in{".ogg":1,".wav":1,".mp3":1}},handle:function(c,d,e,f){function l(r){m||(m=!0,g.preloadedAudios[d]=r,e&&e(c))}function k(){m||(m=!0,g.preloadedAudios[d]=new Audio,f&&f())}var m=!1;if(Cc){try{var n=new Blob([c],{type:Fc(d)})}catch(r){return k()}n=Ec.createObjectURL(n);var p=new Audio;p.addEventListener("canplaythrough",function(){l(p)},!1);p.onerror=function(){if(!m){x("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var r="",u=0,h=0,q=0;q<c.length;q++)for(u=
u<<8|c[q],h+=8;6<=h;){var w=u>>h-6&63;h-=6;r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[w]}2==h?(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],r+="=="):4==h&&(r+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],r+="=");p.src="data:audio/x-"+d.substr(-3)+";base64,"+r;l(p)}};p.src=n;sc(function(){l(p)})}else return k()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||
b.msRequestPointerLock||function(){},b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||document.webkitExitPointerLock||document.msExitPointerLock||function(){},b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",
function(c){!xc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Gc(a,b,c,d){if(b&&g.Pa&&a==g.canvas)return g.Pa;var e;if(b){var f={antialias:!1,alpha:!1,wb:1};if(d)for(var l in d)f[l]=d[l];if("undefined"!==typeof GL&&(e=GL.ub(a,f)))var k=GL.getContext(e).sb}else k=a.getContext("2d");if(!k)return null;c&&(b||na("undefined"===typeof GLctx,"cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Pa=k,b&&GL.xb(e),g.Ab=b,yc.forEach(function(m){m()}),Ac());return k}var Hc=!1,Ic=void 0,Jc=void 0;
function Kc(a,b){function c(){uc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Lc,Ic&&d.requestPointerLock(),uc=!0,Jc?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=G[SDL.screen>>2]|8388608),Mc(g.canvas),Nc()):Mc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Jc?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=G[SDL.screen>>2]&
-8388609),Mc(g.canvas),Nc()):Mc(d));if(g.onFullScreen)g.onFullScreen(uc);if(g.onFullscreen)g.onFullscreen(uc)}Ic=a;Jc=b;"undefined"===typeof Ic&&(Ic=!0);"undefined"===typeof Jc&&(Jc=!1);var d=g.canvas;Hc||(Hc=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?function(){e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT)}:null)||(e.webkitRequestFullScreen?function(){e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT)}:null);e.requestFullscreen()}
function Lc(){if(!uc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Oc=0;function ic(a){if("function"===typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Oc)Oc=b+1E3/60;else for(;b+2>=Oc;)Oc+=1E3/60;setTimeout(a,Math.max(Oc-b,0))}}
function Fc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Pc=[];function Nc(){var a=g.canvas;Pc.forEach(function(b){b(a.width,a.height)})}
function Mc(a,b,c){b&&c?(a.rb=b,a.bb=c):(b=a.rb,c=a.bb);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Jc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Bc,Cc,Dc,Ec,Qc={};
function Rc(){if(!Sc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Qc)void 0===Qc[b]?delete a[b]:a[b]=Qc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Sc=c}return Sc}var Sc,Tc=[null,[],[]];function Uc(a){return 0===a%4&&(0!==a%100||0===a%400)}function Vc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}
var Wc=[31,29,31,30,31,30,31,31,30,31,30,31],Xc=[31,28,31,30,31,30,31,31,30,31,30,31];function Yc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(Uc(a.getFullYear())?Wc:Xc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function Zc(a,b,c,d){function e(h,q,w){for(h="number"===typeof h?h.toString():h||"";h.length<q;)h=w[0]+h;return h}function f(h,q){return e(h,q,"0")}function l(h,q){function w(T){return 0>T?-1:0<T?1:0}var z;0===(z=w(h.getFullYear()-q.getFullYear()))&&0===(z=w(h.getMonth()-q.getMonth()))&&(z=w(h.getDate()-q.getDate()));return z}function k(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function m(h){h=Yc(new Date(h.pa+1900,0,1),h.Ka);var q=new Date(h.getFullYear()+1,0,4),w=k(new Date(h.getFullYear(),0,4));q=k(q);return 0>=l(w,h)?0>=l(q,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var n=E[d+40>>2];d={pb:E[d>>2],ob:E[d+4>>2],Ia:E[d+8>>2],Ca:E[d+12>>2],Aa:E[d+16>>2],pa:E[d+20>>2],Ja:E[d+24>>2],Ka:E[d+28>>2],zb:E[d+32>>2],nb:E[d+
36>>2],qb:n?C(n):""};c=C(c);n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in n)c=c.replace(new RegExp(p,"g"),n[p]);var r="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
u="January February March April May June July August September October November December".split(" ");n={"%a":function(h){return r[h.Ja].substring(0,3)},"%A":function(h){return r[h.Ja]},"%b":function(h){return u[h.Aa].substring(0,3)},"%B":function(h){return u[h.Aa]},"%C":function(h){return f((h.pa+1900)/100|0,2)},"%d":function(h){return f(h.Ca,2)},"%e":function(h){return e(h.Ca,2," ")},"%g":function(h){return m(h).toString().substring(2)},"%G":function(h){return m(h)},"%H":function(h){return f(h.Ia,
2)},"%I":function(h){h=h.Ia;0==h?h=12:12<h&&(h-=12);return f(h,2)},"%j":function(h){return f(h.Ca+Vc(Uc(h.pa+1900)?Wc:Xc,h.Aa-1),3)},"%m":function(h){return f(h.Aa+1,2)},"%M":function(h){return f(h.ob,2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.Ia&&12>h.Ia?"AM":"PM"},"%S":function(h){return f(h.pb,2)},"%t":function(){return"\t"},"%u":function(h){return h.Ja||7},"%U":function(h){var q=new Date(h.pa+1900,0,1),w=0===q.getDay()?q:Yc(q,7-q.getDay());h=new Date(h.pa+1900,h.Aa,h.Ca);return 0>
l(w,h)?f(Math.ceil((31-w.getDate()+(Vc(Uc(h.getFullYear())?Wc:Xc,h.getMonth()-1)-31)+h.getDate())/7),2):0===l(w,q)?"01":"00"},"%V":function(h){var q=new Date(h.pa+1901,0,4),w=k(new Date(h.pa+1900,0,4));q=k(q);var z=Yc(new Date(h.pa+1900,0,1),h.Ka);return 0>l(z,w)?"53":0>=l(q,z)?"01":f(Math.ceil((w.getFullYear()<h.pa+1900?h.Ka+32-w.getDate():h.Ka+1-w.getDate())/7),2)},"%w":function(h){return h.Ja},"%W":function(h){var q=new Date(h.pa,0,1),w=1===q.getDay()?q:Yc(q,0===q.getDay()?1:7-q.getDay()+1);h=
new Date(h.pa+1900,h.Aa,h.Ca);return 0>l(w,h)?f(Math.ceil((31-w.getDate()+(Vc(Uc(h.getFullYear())?Wc:Xc,h.getMonth()-1)-31)+h.getDate())/7),2):0===l(w,q)?"01":"00"},"%y":function(h){return(h.pa+1900).toString().substring(2)},"%Y":function(h){return h.pa+1900},"%z":function(h){h=h.nb;var q=0<=h;h=Math.abs(h)/60;return(q?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.qb},"%%":function(){return"%"}};for(p in n)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),n[p](d)));p=Ta(c,
!1);if(p.length>b)return 0;F.set(p,a);return p.length-1}eb=g.InternalError=db("InternalError");for(var $c=Array(256),ad=0;256>ad;++ad)$c[ad]=String.fromCharCode(ad);hb=$c;ib=g.BindingError=db("BindingError");S.prototype.isAliasOf=function(a){if(!(this instanceof S&&a instanceof S))return!1;var b=this.ka.na.la,c=this.ka.ma,d=a.ka.na.la;for(a=a.ka.ma;b.ta;)c=b.Da(c),b=b.ta;for(;d.ta;)a=d.Da(a),d=d.ta;return b===d&&c===a};
S.prototype.clone=function(){this.ka.ma||jb(this);if(this.ka.Ba)return this.ka.count.value+=1,this;var a=nb,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.ka;a=a(c.call(b,d,{ka:{value:{count:e.count,ya:e.ya,Ba:e.Ba,ma:e.ma,na:e.na,qa:e.qa,sa:e.sa}}}));a.ka.count.value+=1;a.ka.ya=!1;return a};S.prototype["delete"]=function(){this.ka.ma||jb(this);this.ka.ya&&!this.ka.Ba&&R("Object already scheduled for deletion");lb(this);mb(this.ka);this.ka.Ba||(this.ka.qa=void 0,this.ka.ma=void 0)};
S.prototype.isDeleted=function(){return!this.ka.ma};S.prototype.deleteLater=function(){this.ka.ma||jb(this);this.ka.ya&&!this.ka.Ba&&R("Object already scheduled for deletion");pb.push(this);1===pb.length&&ob&&ob(qb);this.ka.ya=!0;return this};V.prototype.Ya=function(a){this.Ta&&(a=this.Ta(a));return a};V.prototype.Qa=function(a){this.ua&&this.ua(a)};V.prototype.argPackAdvance=8;V.prototype.readValueFromPointer=$a;V.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
V.prototype.fromWireType=function(a){function b(){return this.Ha?Db(this.la.za,{na:this.fb,ma:c,sa:this,qa:a}):Db(this.la.za,{na:this,ma:a})}var c=this.Ya(a);if(!c)return this.Qa(a),null;var d=Cb(this.la,c);if(void 0!==d){if(0===d.ka.count.value)return d.ka.ma=c,d.ka.qa=a,d.clone();d=d.clone();this.Qa(a);return d}d=this.la.Xa(c);d=rb[d];if(!d)return b.call(this);d=this.Ga?d.Ua:d.pointerType;var e=Ab(c,this.la,d.la);return null===e?b.call(this):this.Ha?Db(d.la.za,{na:d,ma:e,sa:this,qa:a}):Db(d.la.za,
{na:d,ma:e})};g.getInheritedInstanceCount=function(){return Object.keys(Bb).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in Bb)Bb.hasOwnProperty(b)&&a.push(Bb[b]);return a};g.flushPendingDeletes=qb;g.setDelayFunction=function(a){ob=a;pb.length&&ob&&ob(qb)};Gb=g.UnboundTypeError=db("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<X.length;++b)void 0!==X[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<X.length;++a)if(void 0!==X[a])return X[a];return null};
g.requestFullscreen=function(a,b){Kc(a,b)};g.requestAnimationFrame=function(a){ic(a)};g.setCanvasSize=function(a,b,c){Mc(g.canvas,a,b);c||Nc()};g.pauseMainLoop=function(){Z=null;kc++};g.resumeMainLoop=function(){tc()};g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return Gc(a,b,c,d)};
function Ta(a,b){var c=Array(ua(a)+1);a=ta(a,c,0,c.length);b&&(c.length=a);return c}
var bd={E:function(a){var b=Ya[a];delete Ya[a];var c=b.Ma,d=b.ua,e=b.Ra,f=e.map(function(l){return l.ab}).concat(e.map(function(l){return l.kb}));O([a],f,function(l){var k={};e.forEach(function(m,n){var p=l[n],r=m.Za,u=m.$a,h=l[n+e.length],q=m.jb,w=m.lb;k[m.Wa]={read:function(z){return p.fromWireType(r(u,z))},write:function(z,T){var L=[];q(w,z,h.toWireType(L,T));Za(L)}}});return[{name:b.name,fromWireType:function(m){var n={},p;for(p in k)n[p]=k[p].read(m);d(m);return n},toWireType:function(m,n){for(var p in k)if(!(p in
n))throw new TypeError('Missing field:  "'+p+'"');var r=c();for(p in k)k[p].write(r,n[p]);null!==m&&m.push(d,r);return r},argPackAdvance:8,readValueFromPointer:$a,ra:d}]})},I:function(){},R:function(a,b,c,d,e){var f=gb(c);b=Q(b);P(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,k){return k?d:e},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=F;else if(2===c)k=D;else if(4===c)k=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[l>>
f])},ra:null})},u:function(a,b,c,d,e,f,l,k,m,n,p,r,u){p=Q(p);f=W(e,f);k&&(k=W(l,k));n&&(n=W(m,n));u=W(r,u);var h=bb(p);tb(h,function(){Jb("Cannot construct "+p+" due to unbound types",[d])});O([a,b,c],d?[d]:[],function(q){q=q[0];if(d){var w=q.la;var z=w.za}else z=S.prototype;q=cb(h,function(){if(Object.getPrototypeOf(this)!==T)throw new ib("Use 'new' to construct "+p);if(void 0===L.wa)throw new ib(p+" has no accessible constructor");var vc=L.wa[arguments.length];if(void 0===vc)throw new ib("Tried to invoke ctor of "+
p+" with invalid number of parameters ("+arguments.length+") - expected ("+Object.keys(L.wa).toString()+") parameters instead!");return vc.apply(this,arguments)});var T=Object.create(z,{constructor:{value:q}});q.prototype=T;var L=new ub(p,q,T,u,w,f,k,n);w=new V(p,L,!0,!1);z=new V(p+"*",L,!1,!1);var wc=new V(p+" const*",L,!1,!0);rb[a]={pointerType:z,Ua:wc};Eb(h,q);return[w,z,wc]})},h:function(a,b,c,d,e,f,l){var k=Mb(c,d);b=Q(b);f=W(e,f);O([],[a],function(m){function n(){Jb("Cannot call "+p+" due to unbound types",
k)}m=m[0];var p=m.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var r=m.la.constructor;void 0===r[b]?(n.xa=c-1,r[b]=n):(sb(r,b,p),r[b].oa[c-1]=n);O([],k,function(u){u=Lb(p,[u[0],null].concat(u.slice(1)),null,f,l);void 0===r[b].oa?(u.xa=c-1,r[b]=u):r[b].oa[c-1]=u;return[]});return[]})},T:function(a,b,c,d,e,f){na(0<b);var l=Mb(b,c);e=W(d,e);O([],[a],function(k){k=k[0];var m="constructor "+k.name;void 0===k.la.wa&&(k.la.wa=[]);if(void 0!==k.la.wa[b-1])throw new ib("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+k.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");k.la.wa[b-1]=function(){Jb("Cannot construct "+k.name+" due to unbound types",l)};O([],l,function(n){n.splice(1,0,null);k.la.wa[b-1]=Lb(m,n,null,e,f);return[]});return[]})},m:function(a,b,c,d,e,f,l,k){var m=Mb(c,d);b=Q(b);f=W(e,f);O([],[a],function(n){function p(){Jb("Cannot call "+r+" due to unbound types",m)}n=n[0];var r=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
k&&n.la.gb.push(b);var u=n.la.za,h=u[b];void 0===h||void 0===h.oa&&h.className!==n.name&&h.xa===c-2?(p.xa=c-2,p.className=n.name,u[b]=p):(sb(u,b,r),u[b].oa[c-2]=p);O([],m,function(q){q=Lb(r,q,n,f,l);void 0===u[b].oa?(q.xa=c-2,u[b]=q):u[b].oa[c-2]=q;return[]});return[]})},Q:function(a,b){b=Q(b);P(a,{name:b,fromWireType:function(c){var d=X[c].value;Ob(c);return d},toWireType:function(c,d){return U(d)},argPackAdvance:8,readValueFromPointer:$a,ra:null})},V:function(a,b,c,d){function e(){}c=gb(c);b=Q(b);
e.values={};P(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:function(f,l){return l.value},argPackAdvance:8,readValueFromPointer:Pb(b,c,d),ra:null});tb(b,e)},G:function(a,b,c){var d=Qb(a,"enum");b=Q(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:cb(d.name+"_"+b,function(){})}});a.values[c]=d;a[b]=d},C:function(a,b,c){c=gb(c);b=Q(b);P(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){if("number"!==
typeof e&&"boolean"!==typeof e)throw new TypeError('Cannot convert "'+xb(e)+'" to '+this.name);return e},argPackAdvance:8,readValueFromPointer:Rb(b,c),ra:null})},o:function(a,b,c,d,e){function f(n){return n}b=Q(b);-1===e&&(e=4294967295);var l=gb(c);if(0===d){var k=32-8*c;f=function(n){return n<<k>>>k}}var m=b.includes("unsigned");P(a,{name:b,fromWireType:f,toWireType:function(n,p){if("number"!==typeof p&&"boolean"!==typeof p)throw new TypeError('Cannot convert "'+xb(p)+'" to '+this.name);if(p<d||
p>e)throw new TypeError('Passing a number "'+xb(p)+'" from JS side to C/C++ side to an argument of type "'+b+'", which is outside the valid range ['+d+", "+e+"]!");return m?p>>>0:p|0},argPackAdvance:8,readValueFromPointer:Sb(b,l,0!==d),ra:null})},l:function(a,b,c){function d(f){f>>=2;var l=G;return new e(Ea,l[f+1],l[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array][b];c=Q(c);P(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},
{cb:!0})},D:function(a,b){b=Q(b);var c="std::string"===b;P(a,{name:b,fromWireType:function(d){var e=G[d>>2];if(c)for(var f=d+4,l=0;l<=e;++l){var k=d+4+l;if(l==e||0==B[k]){f=C(f,k-f);if(void 0===m)var m=f;else m+=String.fromCharCode(0),m+=f;f=k+1}}else{m=Array(e);for(l=0;l<e;++l)m[l]=String.fromCharCode(B[d+4+l]);m=m.join("")}K(d);return m},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));var f="string"===typeof e;f||e instanceof Uint8Array||e instanceof Uint8ClampedArray||
e instanceof Int8Array||R("Cannot pass non-string to std::string");var l=(c&&f?function(){return ua(e)}:function(){return e.length})(),k=qa(4+l+1);G[k>>2]=l;if(c&&f)ta(e,B,k+4,l+1);else if(f)for(f=0;f<l;++f){var m=e.charCodeAt(f);255<m&&(K(k),R("String has UTF-16 code units that do not fit in 8 bits"));B[k+4+f]=m}else for(f=0;f<l;++f)B[k+4+f]=e[f];null!==d&&d.push(K,k);return k},argPackAdvance:8,readValueFromPointer:$a,ra:function(d){K(d)}})},z:function(a,b,c){c=Q(c);if(2===b){var d=wa;var e=ya;var f=
za;var l=function(){return xa};var k=1}else 4===b&&(d=Aa,e=Ba,f=Ca,l=function(){return G},k=2);P(a,{name:c,fromWireType:function(m){for(var n=G[m>>2],p=l(),r,u=m+4,h=0;h<=n;++h){var q=m+4+h*b;if(h==n||0==p[q>>k])u=d(u,q-u),void 0===r?r=u:(r+=String.fromCharCode(0),r+=u),u=q+b}K(m);return r},toWireType:function(m,n){"string"!==typeof n&&R("Cannot pass non-string to C++ string type "+c);var p=f(n),r=qa(4+p+b);G[r>>2]=p>>k;e(n,r+4,p+b);null!==m&&m.push(K,r);return r},argPackAdvance:8,readValueFromPointer:$a,
ra:function(m){K(m)}})},F:function(a,b,c,d,e,f){Ya[a]={name:Q(b),Ma:W(c,d),ua:W(e,f),Ra:[]}},r:function(a,b,c,d,e,f,l,k,m,n){Ya[a].Ra.push({Wa:Q(b),ab:c,Za:W(d,e),$a:f,kb:l,jb:W(k,m),lb:n})},S:function(a,b){b=Q(b);P(a,{eb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},k:function(a,b,c){a=Y(a);b=Qb(b,"emval::as");var d=[],e=U(d);E[c>>2]=e;return b.toWireType(d,a)},v:function(a,b,c,d){a=Y(a);c=Tb(b,c);for(var e=Array(b),f=0;f<b;++f){var l=c[f];e[f]=l.readValueFromPointer(d);
d+=l.argPackAdvance}a=a.apply(void 0,e);return U(a)},w:function(a,b,c,d,e){a=Wb[a];b=Y(b);c=Vb(c);var f=[];E[d>>2]=U(f);return a(b,c,f,e)},s:function(a,b,c,d){a=Wb[a];b=Y(b);c=Vb(c);a(b,c,null,d)},a:Ob,b:function(a,b){a=Y(a);b=Y(b);return a==b},j:function(a){if(0===a)return U(Xb());a=Vb(a);return U(Xb()[a])},p:function(a,b){b=Tb(a,b);for(var c=b[0],d=c.name+"_$"+b.slice(1).map(function(n){return n.name}).join("_")+"$",e=["retType"],f=[c],l="",k=0;k<a-1;++k)l+=(0!==k?", ":"")+"arg"+k,e.push("argType"+
k),f.push(b[1+k]);d="return function "+bb("methodCaller_"+d)+"(handle, name, destructors, args) {\n";var m=0;for(k=0;k<a-1;++k)d+="    var arg"+k+" = argType"+k+".readValueFromPointer(args"+(m?"+"+m:"")+");\n",m+=b[k+1].argPackAdvance;d+="    var rv = handle[name]("+l+");\n";for(k=0;k<a-1;++k)b[k+1].deleteObject&&(d+="    argType"+k+".deleteObject(arg"+k+");\n");c.eb||(d+="    return retType.toWireType(destructors, rv);\n");e.push(d+"};\n");a=Kb(e).apply(null,f);return Yb(a)},g:function(a,b){a=Y(a);
b=Y(b);return U(a[b])},c:function(a){4<a&&(X[a].Na+=1)},n:function(a,b,c,d){a=Y(a);var e=Zb[b];if(!e){e="";for(var f=0;f<b;++f)e+=(0!==f?", ":"")+"arg"+f;var l="return function emval_allocator_"+b+"(constructor, argTypes, args) {\n";for(f=0;f<b;++f)l+="var argType"+f+" = requireRegisteredType(Module['HEAP32'][(argTypes >>> 2) + "+f+'], "parameter '+f+'");\nvar arg'+f+" = argType"+f+".readValueFromPointer(args);\nargs += argType"+f+"['argPackAdvance'];\n";e=(new Function("requireRegisteredType","Module",
"__emval_register",l+("var obj = new constructor("+e+");\nreturn __emval_register(obj);\n}\n")))(Qb,g,U);Zb[b]=e}return e(a,c,d)},e:function(a){return U(Vb(a))},i:function(a){Za(X[a].value);Ob(a)},q:function(a,b,c){a=Y(a);b=Y(b);c=Y(c);a[b]=c},d:function(a,b){a=Qb(a,"_emval_take_value");a=a.readValueFromPointer(b);return U(a)},f:function(){ka()},x:function(a,b,c){$b.length=0;var d;for(c>>=2;d=B[b++];)(d=105>d)&&c&1&&c++,$b.push(d?Ga[c++>>1]:E[c]),++c;return Ua[a].apply(null,$b)},A:function(a,b,c,
d,e,f){b=C(b);a=zc[a];var l=-1;e&&(l=a.Ea.length,a.Ea.push({Fa:H.get(e),va:f}),a.Oa++);b={funcName:b,callbackId:l,data:c?new Uint8Array(B.subarray(c,c+d)):0};c?a.worker.postMessage(b,[b.data.buffer]):a.worker.postMessage(b)},H:function(a){a=C(a);var b=zc.length;a={worker:new Worker(a),Ea:[],Oa:0,buffer:0,bufferSize:0};a.worker.onmessage=function(c){if(!A){var d=zc[b];if(d){var e=c.data.callbackId,f=d.Ea[e];if(f)if(c.data.finalResponse&&(d.Oa--,d.Ea[e]=null),c=c.data.data){c.byteLength||(c=new Uint8Array(c));
if(!d.buffer||d.bufferSize<c.length)d.buffer&&K(d.buffer),d.bufferSize=c.length,d.buffer=qa(c.length);B.set(c,d.buffer);f.Fa(d.buffer,c.length,f.va)}else f.Fa(0,0,f.va)}}};zc.push(a);return b},B:function(a){var b=zc[a];b.worker.terminate();b.buffer&&K(b.buffer);zc[a]=null},K:function(a,b,c){B.copyWithin(a,b,b+c)},W:function(){Z=null;kc++},y:function(a){var b=B.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);d=Math.max(a,d);0<d%65536&&(d+=65536-
d%65536);a:{try{la.grow(Math.min(2147483648,d)-Ea.byteLength+65535>>>16);Ha();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},U:function(){tc()},P:function(a,b,c){a=H.get(a);jc(a,b,c)},M:function(a,b){var c=0;Rc().forEach(function(d,e){var f=b+c;e=E[a+4*e>>2]=f;for(f=0;f<d.length;++f)F[e++>>0]=d.charCodeAt(f);F[e>>0]=0;c+=d.length+1});return 0},N:function(a,b){var c=Rc();E[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});E[b>>2]=d;return 0},O:function(a,b,c,d){for(var e=0,f=
0;f<c;f++){for(var l=E[b+8*f>>2],k=E[b+(8*f+4)>>2],m=0;m<k;m++){var n=B[l+m],p=Tc[a];0===n||10===n?((1===a?x:y)(sa(p,0)),p.length=0):p.push(n)}e+=k}E[d>>2]=e;return 0},t:function(a){var b=Date.now();E[a>>2]=b/1E3|0;E[a+4>>2]=b%1E3*1E3|0;return 0},J:function(){},L:function(a,b,c,d){return Zc(a,b,c,d)},X:function(a){var b=Date.now()/1E3|0;a&&(E[a>>2]=b);return b}};
(function(){function a(e){g.asm=e.exports;la=g.asm.Y;Ha();H=g.asm.ea;Ja.unshift(g.asm.Z);I--;g.monitorRunDependencies&&g.monitorRunDependencies(I);0==I&&(null!==Na&&(clearInterval(Na),Na=null),Oa&&(e=Oa,Oa=null,e()))}function b(e){a(e.instance)}function c(e){return Sa().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){y("failed to asynchronously prepare wasm: "+f);ka(f)})}var d={a:bd};I++;g.monitorRunDependencies&&g.monitorRunDependencies(I);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(e){return y("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ja||"function"!==typeof WebAssembly.instantiateStreaming||Pa()||"function"!==typeof fetch?c(b):fetch(J,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){y("wasm streaming compile failed: "+f);y("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.Z).apply(null,arguments)};var qa=g._malloc=function(){return(qa=g._malloc=g.asm._).apply(null,arguments)},K=g._free=function(){return(K=g._free=g.asm.$).apply(null,arguments)};g._main=function(){return(g._main=g.asm.aa).apply(null,arguments)};var Ib=g.___getTypeName=function(){return(Ib=g.___getTypeName=g.asm.ba).apply(null,arguments)};
g.___embind_register_native_and_builtin_types=function(){return(g.___embind_register_native_and_builtin_types=g.asm.ca).apply(null,arguments)};var pa=g.stackAlloc=function(){return(pa=g.stackAlloc=g.asm.da).apply(null,arguments)};g.dynCall_viijj=function(){return(g.dynCall_viijj=g.asm.fa).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.ga).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.ha).apply(null,arguments)};
g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.ia).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.ja).apply(null,arguments)};g.print=x;var cd;function Xa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}Oa=function dd(){cd||ed();cd||(Oa=dd)};
function ed(a){function b(){if(!cd&&(cd=!0,g.calledRun=!0,!A)){Va(Ja);Va(Ka);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();if(fd){var c=a,d=g._main;c=c||[];var e=c.length+1,f=pa(4*(e+1));E[f>>2]=Da(ea);for(var l=1;l<e;l++)E[(f>>2)+l]=Da(c[l-1]);E[(f>>2)+e]=0;try{var k=d(e,f);lc(k)}catch(m){Wa(m)}finally{}}if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;)c=g.postRun.shift(),La.unshift(c);Va(La)}}a=a||da;if(!(0<I)){if(g.preRun)for("function"==typeof g.preRun&&
(g.preRun=[g.preRun]);g.preRun.length;)Ma();Va(Ia);0<I||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},1);b()},1)):b())}}g.run=ed;function lc(a){ma=ma=a;if(!noExitRuntime){if(g.onExit)g.onExit(a);A=!0}fa(a,new Xa(a))}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var fd=!0;g.noInitialRun&&(fd=!1);ed();


  return TWASMModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = TWASMModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return TWASMModule; });
else if (typeof exports === 'object')
  exports["TWASMModule"] = TWASMModule;
