
var g;g||(g=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},g),ba=[],ca="./this.program",da=(a,b)=>{throw b;},q="",ea;q=self.location.href;q=0!==q.indexOf("blob:")?q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):"";ea=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)};var fa=g.print||console.log.bind(console),v=g.printErr||console.warn.bind(console);Object.assign(g,aa);aa=null;
g.arguments&&(ba=g.arguments);g.thisProgram&&(ca=g.thisProgram);g.quit&&(da=g.quit);var ha;g.wasmBinary&&(ha=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&x("no native wasm support detected");var ia,y=!1,ja="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function z(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ja)return ja.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function ka(a,b,c,d){if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|f>>12}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0}}
function la(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var ma,B,C,D,na,E,F,oa,pa;function qa(){var a=ia.buffer;ma=a;g.HEAP8=B=new Int8Array(a);g.HEAP16=D=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=C=new Uint8Array(a);g.HEAPU16=na=new Uint16Array(a);g.HEAPU32=F=new Uint32Array(a);g.HEAPF32=oa=new Float32Array(a);g.HEAPF64=pa=new Float64Array(a)}var ra,sa=[],ta=[],ua=[],va=[],wa=!1;
function xa(){var a=g.preRun.shift();sa.unshift(a)}var G=0,ya=null,za=null;function x(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";v(a);y=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}function Aa(){return H.startsWith("data:application/octet-stream;base64,")}var H;H="thing.wasm.worker.wasm";if(!Aa()){var Ba=H;H=g.locateFile?g.locateFile(Ba,q):q+Ba}
function Ca(){var a=H;try{if(a==H&&ha)return new Uint8Array(ha);if(ea)return ea(a);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}function Da(){return ha||"function"!=typeof fetch?Promise.resolve().then(function(){return Ca()}):fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return Ca()})}
var Ea={56592:()=>{function a(b){try{return decodeURIComponent(escape(b))}catch(c){return String.fromCharCode(65533)}}window.decodeBufferToString=function(b){var c=b.length,d="",e="";c=Math.min(b.length,c||Infinity);for(var f=0;f<c;f++)127>=b[f]?(d+=a(e)+String.fromCharCode(b[f]),e=""):e+="%"+b[f].toString(16);return d+a(e)}}};function Fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Ga(a){for(;0<a.length;)a.shift()(g)}var Ha={};
function Ia(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Ja(a){return this.fromWireType(E[a>>2])}var I={},J={},Ka={};function La(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ma(a,b){a=La(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Na(a){var b=Error,c=Ma(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Oa=void 0;function Pa(a){throw new Oa(a);}
function K(a,b,c){function d(h){h=c(h);h.length!==a.length&&Pa("Mismatched type converter count");for(var m=0;m<a.length;++m)L(a[m],h[m])}a.forEach(function(h){Ka[h]=b});var e=Array(b.length),f=[],l=0;b.forEach((h,m)=>{J.hasOwnProperty(h)?e[m]=J[h]:(f.push(h),I.hasOwnProperty(h)||(I[h]=[]),I[h].push(()=>{e[m]=J[h];++l;l===f.length&&d(e)}))});0===f.length&&d(e)}
function Qa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ra=void 0;function M(a){for(var b="";C[a];)b+=Ra[C[a++]];return b}var O=void 0;function P(a){throw new O(a);}
function L(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||P('type "'+d+'" must have a positive integer typeid pointer');if(J.hasOwnProperty(a)){if(c.ib)return;P("Cannot register type '"+d+"' twice")}J[a]=b;delete Ka[a];I.hasOwnProperty(a)&&(b=I[a],delete I[a],b.forEach(e=>e()))}function Sa(a){P(a.oa.ra.pa.name+" instance already deleted")}var Ta=!1;function Ua(){}
function Va(a){--a.count.value;0===a.count.value&&(a.ta?a.va.ya(a.ta):a.ra.pa.ya(a.qa))}function Wa(a,b,c){if(b===c)return a;if(void 0===c.wa)return null;a=Wa(a,b,c.wa);return null===a?null:c.$a(a)}var Xa={},Ya=[];function Za(){for(;Ya.length;){var a=Ya.pop();a.oa.Da=!1;a["delete"]()}}var $a=void 0,ab={};function bb(a,b){for(void 0===b&&P("ptr should not be undefined");a.wa;)b=a.Ga(b),a=a.wa;return ab[b]}
function cb(a,b){b.ra&&b.qa||Pa("makeClassHandle requires ptr and ptrType");!!b.va!==!!b.ta&&Pa("Both smartPtrType and smartPtr must be specified");b.count={value:1};return db(Object.create(a,{oa:{value:b}}))}function db(a){if("undefined"===typeof FinalizationRegistry)return db=b=>b,a;Ta=new FinalizationRegistry(b=>{Va(b.oa)});db=b=>{var c=b.oa;c.ta&&Ta.register(b,{oa:c},b);return b};Ua=b=>{Ta.unregister(b)};return db(a)}function R(){}
function eb(a,b,c){if(void 0===a[b].sa){var d=a[b];a[b]=function(){a[b].sa.hasOwnProperty(arguments.length)||P("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].sa+")!");return a[b].sa[arguments.length].apply(this,arguments)};a[b].sa=[];a[b].sa[d.Ca]=d}}
function fb(a,b){g.hasOwnProperty(a)?(P("Cannot register public name '"+a+"' twice"),eb(g,a,a),g.hasOwnProperty(void 0)&&P("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),g[a].sa[void 0]=b):g[a]=b}function gb(a,b,c,d,e,f,l,h){this.name=a;this.constructor=b;this.Ea=c;this.ya=d;this.wa=e;this.bb=f;this.Ga=l;this.$a=h;this.lb=[]}
function hb(a,b,c){for(;b!==c;)b.Ga||P("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Ga(a),b=b.wa;return a}function ib(a,b){if(null===b)return this.Oa&&P("null is not a valid "+this.name),0;b.oa||P('Cannot pass "'+jb(b)+'" as a '+this.name);b.oa.qa||P("Cannot pass deleted object as a pointer of type "+this.name);return hb(b.oa.qa,b.oa.ra.pa,this.pa)}
function kb(a,b){if(null===b){this.Oa&&P("null is not a valid "+this.name);if(this.Ja){var c=this.Pa();null!==a&&a.push(this.ya,c);return c}return 0}b.oa||P('Cannot pass "'+jb(b)+'" as a '+this.name);b.oa.qa||P("Cannot pass deleted object as a pointer of type "+this.name);!this.Ia&&b.oa.ra.Ia&&P("Cannot convert argument of type "+(b.oa.va?b.oa.va.name:b.oa.ra.name)+" to parameter type "+this.name);c=hb(b.oa.qa,b.oa.ra.pa,this.pa);if(this.Ja)switch(void 0===b.oa.ta&&P("Passing raw pointer to smart pointer is illegal"),
this.rb){case 0:b.oa.va===this?c=b.oa.ta:P("Cannot convert argument of type "+(b.oa.va?b.oa.va.name:b.oa.ra.name)+" to parameter type "+this.name);break;case 1:c=b.oa.ta;break;case 2:if(b.oa.va===this)c=b.oa.ta;else{var d=b.clone();c=this.nb(c,S(function(){d["delete"]()}));null!==a&&a.push(this.ya,c)}break;default:P("Unsupporting sharing policy")}return c}
function lb(a,b){if(null===b)return this.Oa&&P("null is not a valid "+this.name),0;b.oa||P('Cannot pass "'+jb(b)+'" as a '+this.name);b.oa.qa||P("Cannot pass deleted object as a pointer of type "+this.name);b.oa.ra.Ia&&P("Cannot convert argument of type "+b.oa.ra.name+" to parameter type "+this.name);return hb(b.oa.qa,b.oa.ra.pa,this.pa)}
function T(a,b,c,d){this.name=a;this.pa=b;this.Oa=c;this.Ia=d;this.Ja=!1;this.ya=this.nb=this.Pa=this.Ya=this.rb=this.kb=void 0;void 0!==b.wa?this.toWireType=kb:(this.toWireType=d?ib:lb,this.ua=null)}function mb(a,b){g.hasOwnProperty(a)||Pa("Replacing nonexistant public symbol");g[a]=b;g[a].Ca=void 0}var nb=[];function ob(a){var b=nb[a];b||(a>=nb.length&&(nb.length=a+1),nb[a]=b=ra.get(a));return b}
function pb(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=g["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=ob(b).apply(null,c);return d}}function U(a,b){a=M(a);var c=a.includes("j")?pb(a,b):ob(b);"function"!=typeof c&&P("unknown function pointer with signature "+a+": "+b);return c}var qb=void 0;function rb(a){a=sb(a);var b=M(a);V(a);return b}
function tb(a,b){function c(f){e[f]||J[f]||(Ka[f]?Ka[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new qb(a+": "+d.map(rb).join([", "]));}function ub(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ma(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function vb(a,b,c,d,e){var f=b.length;2>f&&P("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,h=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].ua){h=!0;break}var m="void"!==b[0].name,n="",p="";for(c=0;c<f-2;++c)n+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+La(a)+"("+n+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";h&&(a+="var destructors = [];\n");var t=h?"destructors":"null";n="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[P,d,e,Ia,b[0],b[1]];l&&(a+="var thisWired = classParam.toWireType("+t+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+t+", arg"+c+"); // "+b[c+2].name+"\n",n.push("argType"+c),d.push(b[c+2]);l&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(m?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(h)a+=
"runDestructors(destructors);\n";else for(c=l?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].ua&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",n.push(f+"_dtor"),d.push(b[c].ua));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");n.push(a+"}\n");return ub(n).apply(null,d)}function wb(a,b){for(var c=[],d=0;d<a;d++)c.push(F[b+4*d>>2]);return c}var xb=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function yb(a){4<a&&0===--W[a].Qa&&(W[a]=void 0,xb.push(a))}
var X=a=>{a||P("Cannot use deleted val. handle = "+a);return W[a].value},S=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=xb.length?xb.pop():W.length;W[b]={Qa:1,value:a};return b}};
function zb(a,b,c){switch(b){case 0:return function(d){return this.fromWireType((c?B:C)[d])};case 1:return function(d){return this.fromWireType((c?D:na)[d>>1])};case 2:return function(d){return this.fromWireType((c?E:F)[d>>2])};default:throw new TypeError("Unknown integer type: "+a);}}function Ab(a,b){var c=J[a];void 0===c&&P(b+" has unknown type "+rb(a));return c}function jb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Bb(a,b){switch(b){case 2:return function(c){return this.fromWireType(oa[c>>2])};case 3:return function(c){return this.fromWireType(pa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Cb(a,b,c){switch(b){case 0:return c?function(d){return B[d]}:function(d){return C[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return na[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return F[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Db="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function Eb(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&na[c];)++c;c<<=1;if(32<c-a&&Db)return Db.decode(C.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=D[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Fb(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d}function Gb(a){return 2*a.length}
function Hb(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function Ib(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}
function Jb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Kb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Ab(F[b+4*d>>2],"parameter "+d);return c}var Lb={};function Mb(a){var b=Lb[a];return void 0===b?M(a):b}var Nb=[];function Ob(){return"object"==typeof globalThis?globalThis:Function("return this")()}function Pb(a){var b=Nb.length;Nb.push(a);return b}var Qb=[];
function Rb(a){for(var b="",c=0;c<a;++c)b+=(0!==c?", ":"")+"arg"+c;var d="return function emval_allocator_"+a+"(constructor, argTypes, args) {\n  var HEAPU32 = getMemory();\n";for(c=0;c<a;++c)d+="var argType"+c+" = requireRegisteredType(HEAPU32[((argTypes)>>2)], 'parameter "+c+"');\nvar arg"+c+" = argType"+c+".readValueFromPointer(args);\nargs += argType"+c+"['argPackAdvance'];\nargTypes += 4;\n";return(new Function("requireRegisteredType","Module","valueToHandle","getMemory",d+("var obj = new constructor("+
b+");\nreturn valueToHandle(obj);\n}\n")))(Ab,g,S,()=>F)}var Sb={};function Tb(a){return 0===a%4&&(0!==a%100||0===a%400)}var Ub=[0,31,60,91,121,152,182,213,244,274,305,335],Vb=[0,31,59,90,120,151,181,212,243,273,304,334];function Wb(a){return(Tb(a.getFullYear())?Ub:Vb)[a.getMonth()]+a.getDate()-1}function Xb(a){var b=la(a)+1,c=Yb(b);c&&ka(a,B,c,b);return c}var Zb=[];
function $b(a,b){ac=a;bc=b;if(cc)if(dc||(dc=!0),0==a)Y=function(){var d=Math.max(0,ec+b-fc())|0;setTimeout(gc,d)};else if(1==a)Y=function(){hc(gc)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);void 0===g.setImmediates&&(g.setImmediates=[]);g.setImmediates.push(d);postMessage({target:"setimmediate"})}}Y=function(){setImmediate(gc)}}}
var fc;fc=()=>performance.now();function ic(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);y=!0}da(a,new Fa(a))}function jc(a){a instanceof Fa||"unwind"==a||da(1,a)}
function kc(a,b,c,d,e){!cc||x("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");cc=a;lc=d;var f=Z;dc=!1;gc=function(){if(!y)if(0<mc.length){var l=Date.now(),h=mc.shift();h.Na(h.Ma);if(nc){var m=nc,n=0==m%1?m-1:Math.floor(m);nc=h.yb?n:(8*m+(n+.5))/9}fa('main loop blocker "'+h.name+'" took '+(Date.now()-l)+" ms");g.setStatus&&(l=g.statusMessage||"Please wait...",
h=nc,m=oc.Ab,h?h<m?g.setStatus(l+" ("+(m-h)+"/"+m+")"):g.setStatus(l):g.setStatus(""));f<Z||setTimeout(gc,0)}else f<Z||(pc=pc+1|0,1==ac&&1<bc&&0!=pc%bc?Y():(0==ac&&(ec=fc()),y||g.preMainLoop&&!1===g.preMainLoop()||(qc(a),g.postMainLoop&&g.postMainLoop()),f<Z||("object"==typeof SDL&&SDL.audio&&SDL.audio.mb&&SDL.audio.mb(),Y())))};e||(b&&0<b?$b(0,1E3/b):$b(1,1),Y());if(c)throw"unwind";}function qc(a){if(!y)try{a()}catch(b){jc(b)}}function tc(a){setTimeout(function(){qc(a)},1E4)}
function uc(a){vc||(vc={});vc[a]||(vc[a]=1,v(a))}var vc,dc=!1,Y=null,Z=0,cc=null,lc=0,ac=0,bc=0,pc=0,mc=[];function wc(){Z++;var a=ac,b=bc,c=cc;cc=null;kc(c,0,!1,lc,!0);$b(a,b);Y()}var oc={},ec,gc,nc,xc=!1,yc=!1,zc=[],Ac=[];
function Bc(){function a(){yc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!Cc){Cc=!0;try{Dc=!0}catch(c){Dc=!1,v("warning: no blob constructor, cannot create blobs with mimetypes")}Ec="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Dc?null:v("warning: no BlobBuilder");Fc="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;g.Wa||"undefined"!=typeof Fc||(v("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.Wa=!0);g.preloadPlugins.push({canHandle:function(c){return!g.Wa&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var l=null;if(Dc)try{l=new Blob([c],{type:Gc(d)}),l.size!==c.length&&(l=new Blob([(new Uint8Array(c)).buffer],{type:Gc(d)}))}catch(n){uc("Blob constructor present but fails: "+
n+"; falling back to blob builder")}l||(l=new Ec,l.append((new Uint8Array(c)).buffer),l=l.getBlob());var h=Fc.createObjectURL(l),m=new Image;m.onload=()=>{m.complete||x("Image "+d+" could not be decoded");var n=document.createElement("canvas");n.width=m.width;n.height=m.height;n.getContext("2d").drawImage(m,0,0);Fc.revokeObjectURL(h);e&&e(c)};m.onerror=()=>{fa("Image "+h+" could not be decoded");f&&f()};m.src=h}});g.preloadPlugins.push({canHandle:function(c){return!g.Db&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,f){function l(){m||(m=!0,e&&e(c))}function h(){m||(m=!0,new Audio,f&&f())}var m=!1;if(Dc){try{var n=new Blob([c],{type:Gc(d)})}catch(t){return h()}n=Fc.createObjectURL(n);var p=new Audio;p.addEventListener("canplaythrough",()=>l(p),!1);p.onerror=function(){if(!m){v("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var t="",u=0,k=0,r=0;r<c.length;r++)for(u=u<<8|c[r],k+=8;6<=k;){var w=u>>k-6&63;k-=6;t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[w]}2==
k?(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],t+="=="):4==k&&(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],t+="=");p.src="data:audio/x-"+d.substr(-3)+";base64,"+t;l(p)}};p.src=n;tc(function(){l(p)})}else return h()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!yc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Hc(a,b,c,d){if(b&&g.Ta&&a==g.canvas)return g.Ta;var e;if(b){var f={antialias:!1,alpha:!1,Bb:1};if(d)for(var l in d)f[l]=d[l];if("undefined"!=typeof GL&&(e=GL.zb(a,f)))var h=GL.getContext(e).xb}else h=a.getContext("2d");if(!h)return null;c&&(b||"undefined"==typeof GLctx||x("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Ta=h,b&&GL.Cb(e),g.Fb=b,zc.forEach(function(m){m()}),Bc());return h}var Ic=!1,Jc=void 0,Kc=void 0;
function Lc(a,b){function c(){xc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Mc,Jc&&d.requestPointerLock(),xc=!0,Kc?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=F[SDL.screen>>2]|8388608),Nc(g.canvas),Oc()):Nc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Kc?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=F[SDL.screen>>2]&
-8388609),Nc(g.canvas),Oc()):Nc(d));if(g.onFullScreen)g.onFullScreen(xc);if(g.onFullscreen)g.onFullscreen(xc)}Jc=a;Kc=b;"undefined"==typeof Jc&&(Jc=!0);"undefined"==typeof Kc&&(Kc=!1);var d=g.canvas;Ic||(Ic=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Mc(){if(!xc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Pc=0;function hc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Pc)Pc=b+1E3/60;else for(;b+2>=Pc;)Pc+=1E3/60;setTimeout(a,Math.max(Pc-b,0))}}
function Gc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Qc=[];function Oc(){var a=g.canvas;Qc.forEach(function(b){b(a.width,a.height)})}
function Nc(a,b,c){b&&c?(a.wb=b,a.hb=c):(b=a.wb,c=a.hb);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Kc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Cc,Dc,Ec,Fc,Rc={};
function Sc(){if(!Tc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Rc)void 0===Rc[b]?delete a[b]:a[b]=Rc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Tc=c}return Tc}var Tc,Uc=[null,[],[]];
function Vc(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}return()=>x("randomDevice")}function Wc(a,b){Wc.Xa||(Wc.Xa=Vc());for(var c=0;c<b;c++)B[a+c>>0]=Wc.Xa();return 0}var Xc=[31,29,31,30,31,30,31,31,30,31,30,31],Yc=[31,28,31,30,31,30,31,31,30,31,30,31];function Zc(a){var b=Array(la(a)+1);ka(a,b,0,b.length);return b}
function $c(a,b,c,d){function e(k,r,w){for(k="number"==typeof k?k.toString():k||"";k.length<r;)k=w[0]+k;return k}function f(k,r){return e(k,r,"0")}function l(k,r){function w(Q){return 0>Q?-1:0<Q?1:0}var A;0===(A=w(k.getFullYear()-r.getFullYear()))&&0===(A=w(k.getMonth()-r.getMonth()))&&(A=w(k.getDate()-r.getDate()));return A}function h(k){switch(k.getDay()){case 0:return new Date(k.getFullYear()-1,11,29);case 1:return k;case 2:return new Date(k.getFullYear(),0,3);case 3:return new Date(k.getFullYear(),
0,2);case 4:return new Date(k.getFullYear(),0,1);case 5:return new Date(k.getFullYear()-1,11,31);case 6:return new Date(k.getFullYear()-1,11,30)}}function m(k){var r=k.Aa;for(k=new Date((new Date(k.Ba+1900,0,1)).getTime());0<r;){var w=k.getMonth(),A=(Tb(k.getFullYear())?Xc:Yc)[w];if(r>A-k.getDate())r-=A-k.getDate()+1,k.setDate(1),11>w?k.setMonth(w+1):(k.setMonth(0),k.setFullYear(k.getFullYear()+1));else{k.setDate(k.getDate()+r);break}}w=new Date(k.getFullYear()+1,0,4);r=h(new Date(k.getFullYear(),
0,4));w=h(w);return 0>=l(r,k)?0>=l(w,k)?k.getFullYear()+1:k.getFullYear():k.getFullYear()-1}var n=E[d+40>>2];d={ub:E[d>>2],tb:E[d+4>>2],Ka:E[d+8>>2],Ra:E[d+12>>2],La:E[d+16>>2],Ba:E[d+20>>2],xa:E[d+24>>2],Aa:E[d+28>>2],Eb:E[d+32>>2],sb:E[d+36>>2],vb:n?n?z(C,n):"":""};c=c?z(C,c):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in n)c=c.replace(new RegExp(p,"g"),n[p]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),u="January February March April May June July August September October November December".split(" ");n={"%a":function(k){return t[k.xa].substring(0,3)},"%A":function(k){return t[k.xa]},"%b":function(k){return u[k.La].substring(0,
3)},"%B":function(k){return u[k.La]},"%C":function(k){return f((k.Ba+1900)/100|0,2)},"%d":function(k){return f(k.Ra,2)},"%e":function(k){return e(k.Ra,2," ")},"%g":function(k){return m(k).toString().substring(2)},"%G":function(k){return m(k)},"%H":function(k){return f(k.Ka,2)},"%I":function(k){k=k.Ka;0==k?k=12:12<k&&(k-=12);return f(k,2)},"%j":function(k){for(var r=0,w=0;w<=k.La-1;r+=(Tb(k.Ba+1900)?Xc:Yc)[w++]);return f(k.Ra+r,3)},"%m":function(k){return f(k.La+1,2)},"%M":function(k){return f(k.tb,
2)},"%n":function(){return"\n"},"%p":function(k){return 0<=k.Ka&&12>k.Ka?"AM":"PM"},"%S":function(k){return f(k.ub,2)},"%t":function(){return"\t"},"%u":function(k){return k.xa||7},"%U":function(k){return f(Math.floor((k.Aa+7-k.xa)/7),2)},"%V":function(k){var r=Math.floor((k.Aa+7-(k.xa+6)%7)/7);2>=(k.xa+371-k.Aa-2)%7&&r++;if(r)53==r&&(w=(k.xa+371-k.Aa)%7,4==w||3==w&&Tb(k.Ba)||(r=1));else{r=52;var w=(k.xa+7-k.Aa-1)%7;(4==w||5==w&&Tb(k.Ba%400-1))&&r++}return f(r,2)},"%w":function(k){return k.xa},"%W":function(k){return f(Math.floor((k.Aa+
7-(k.xa+6)%7)/7),2)},"%y":function(k){return(k.Ba+1900).toString().substring(2)},"%Y":function(k){return k.Ba+1900},"%z":function(k){k=k.sb;var r=0<=k;k=Math.abs(k)/60;return(r?"+":"-")+String("0000"+(k/60*100+k%60)).slice(-4)},"%Z":function(k){return k.vb},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(p in n)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),n[p](d)));c=c.replace(/\0\0/g,"%");p=Zc(c);if(p.length>b)return 0;B.set(p,a);return p.length-1}Oa=g.InternalError=Na("InternalError");
for(var ad=Array(256),bd=0;256>bd;++bd)ad[bd]=String.fromCharCode(bd);Ra=ad;O=g.BindingError=Na("BindingError");R.prototype.isAliasOf=function(a){if(!(this instanceof R&&a instanceof R))return!1;var b=this.oa.ra.pa,c=this.oa.qa,d=a.oa.ra.pa;for(a=a.oa.qa;b.wa;)c=b.Ga(c),b=b.wa;for(;d.wa;)a=d.Ga(a),d=d.wa;return b===d&&c===a};
R.prototype.clone=function(){this.oa.qa||Sa(this);if(this.oa.Fa)return this.oa.count.value+=1,this;var a=db,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.oa;a=a(c.call(b,d,{oa:{value:{count:e.count,Da:e.Da,Fa:e.Fa,qa:e.qa,ra:e.ra,ta:e.ta,va:e.va}}}));a.oa.count.value+=1;a.oa.Da=!1;return a};R.prototype["delete"]=function(){this.oa.qa||Sa(this);this.oa.Da&&!this.oa.Fa&&P("Object already scheduled for deletion");Ua(this);Va(this.oa);this.oa.Fa||(this.oa.ta=void 0,this.oa.qa=void 0)};
R.prototype.isDeleted=function(){return!this.oa.qa};R.prototype.deleteLater=function(){this.oa.qa||Sa(this);this.oa.Da&&!this.oa.Fa&&P("Object already scheduled for deletion");Ya.push(this);1===Ya.length&&$a&&$a(Za);this.oa.Da=!0;return this};g.getInheritedInstanceCount=function(){return Object.keys(ab).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in ab)ab.hasOwnProperty(b)&&a.push(ab[b]);return a};g.flushPendingDeletes=Za;g.setDelayFunction=function(a){$a=a;Ya.length&&$a&&$a(Za)};
T.prototype.cb=function(a){this.Ya&&(a=this.Ya(a));return a};T.prototype.Ua=function(a){this.ya&&this.ya(a)};T.prototype.argPackAdvance=8;T.prototype.readValueFromPointer=Ja;T.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
T.prototype.fromWireType=function(a){function b(){return this.Ja?cb(this.pa.Ea,{ra:this.kb,qa:c,va:this,ta:a}):cb(this.pa.Ea,{ra:this,qa:a})}var c=this.cb(a);if(!c)return this.Ua(a),null;var d=bb(this.pa,c);if(void 0!==d){if(0===d.oa.count.value)return d.oa.qa=c,d.oa.ta=a,d.clone();d=d.clone();this.Ua(a);return d}d=this.pa.bb(c);d=Xa[d];if(!d)return b.call(this);d=this.Ia?d.Za:d.pointerType;var e=Wa(c,this.pa,d.pa);return null===e?b.call(this):this.Ja?cb(d.pa.Ea,{ra:d,qa:e,va:this,ta:a}):cb(d.pa.Ea,
{ra:d,qa:e})};qb=g.UnboundTypeError=Na("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};g.requestFullscreen=function(a,b){Lc(a,b)};g.requestAnimationFrame=function(a){hc(a)};g.setCanvasSize=function(a,b,c){Nc(g.canvas,a,b);c||Oc()};g.pauseMainLoop=function(){Y=null;Z++};g.resumeMainLoop=function(){wc()};
g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return Hc(a,b,c,d)};
var ed={F:function(a){var b=Ha[a];delete Ha[a];var c=b.Pa,d=b.ya,e=b.Va,f=e.map(l=>l.gb).concat(e.map(l=>l.pb));K([a],f,l=>{var h={};e.forEach((m,n)=>{var p=l[n],t=m.eb,u=m.fb,k=l[n+e.length],r=m.ob,w=m.qb;h[m.ab]={read:A=>p.fromWireType(t(u,A)),write:(A,Q)=>{var N=[];r(w,A,k.toWireType(N,Q));Ia(N)}}});return[{name:b.name,fromWireType:function(m){var n={},p;for(p in h)n[p]=h[p].read(m);d(m);return n},toWireType:function(m,n){for(var p in h)if(!(p in n))throw new TypeError('Missing field:  "'+p+'"');
var t=c();for(p in h)h[p].write(t,n[p]);null!==m&&m.push(d,t);return t},argPackAdvance:8,readValueFromPointer:Ja,ua:d}]})},I:function(){},V:function(a,b,c,d,e){var f=Qa(c);b=M(b);L(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,h){return h?d:e},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var h=B;else if(2===c)h=D;else if(4===c)h=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(h[l>>f])},ua:null})},u:function(a,b,c,d,e,f,l,h,m,
n,p,t,u){p=M(p);f=U(e,f);h&&(h=U(l,h));n&&(n=U(m,n));u=U(t,u);var k=La(p);fb(k,function(){tb("Cannot construct "+p+" due to unbound types",[d])});K([a,b,c],d?[d]:[],function(r){r=r[0];if(d){var w=r.pa;var A=w.Ea}else A=R.prototype;r=Ma(k,function(){if(Object.getPrototypeOf(this)!==Q)throw new O("Use 'new' to construct "+p);if(void 0===N.za)throw new O(p+" has no accessible constructor");var rc=N.za[arguments.length];if(void 0===rc)throw new O("Tried to invoke ctor of "+p+" with invalid number of parameters ("+
arguments.length+") - expected ("+Object.keys(N.za).toString()+") parameters instead!");return rc.apply(this,arguments)});var Q=Object.create(A,{constructor:{value:r}});r.prototype=Q;var N=new gb(p,r,Q,u,w,f,h,n);w=new T(p,N,!0,!1);A=new T(p+"*",N,!1,!1);var sc=new T(p+" const*",N,!1,!0);Xa[a]={pointerType:A,Za:sc};mb(k,r);return[w,A,sc]})},k:function(a,b,c,d,e,f,l){var h=wb(c,d);b=M(b);f=U(e,f);K([],[a],function(m){function n(){tb("Cannot call "+p+" due to unbound types",h)}m=m[0];var p=m.name+"."+
b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var t=m.pa.constructor;void 0===t[b]?(n.Ca=c-1,t[b]=n):(eb(t,b,p),t[b].sa[c-1]=n);K([],h,function(u){u=vb(p,[u[0],null].concat(u.slice(1)),null,f,l);void 0===t[b].sa?(u.Ca=c-1,t[b]=u):t[b].sa[c-1]=u;return[]});return[]})},w:function(a,b,c,d,e,f){0<b||x();var l=wb(b,c);e=U(d,e);K([],[a],function(h){h=h[0];var m="constructor "+h.name;void 0===h.pa.za&&(h.pa.za=[]);if(void 0!==h.pa.za[b-1])throw new O("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+h.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");h.pa.za[b-1]=()=>{tb("Cannot construct "+h.name+" due to unbound types",l)};K([],l,function(n){n.splice(1,0,null);h.pa.za[b-1]=vb(m,n,null,e,f);return[]});return[]})},l:function(a,b,c,d,e,f,l,h){var m=wb(c,d);b=M(b);f=U(e,f);K([],[a],function(n){function p(){tb("Cannot call "+t+" due to unbound types",m)}n=n[0];var t=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
h&&n.pa.lb.push(b);var u=n.pa.Ea,k=u[b];void 0===k||void 0===k.sa&&k.className!==n.name&&k.Ca===c-2?(p.Ca=c-2,p.className=n.name,u[b]=p):(eb(u,b,t),u[b].sa[c-2]=p);K([],m,function(r){r=vb(t,r,n,f,l);void 0===u[b].sa?(r.Ca=c-2,u[b]=r):u[b].sa[c-2]=r;return[]});return[]})},U:function(a,b){b=M(b);L(a,{name:b,fromWireType:function(c){var d=X(c);yb(c);return d},toWireType:function(c,d){return S(d)},argPackAdvance:8,readValueFromPointer:Ja,ua:null})},H:function(a,b,c,d){function e(){}c=Qa(c);b=M(b);e.values=
{};L(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:function(f,l){return l.value},argPackAdvance:8,readValueFromPointer:zb(b,c,d),ua:null});fb(b,e)},x:function(a,b,c){var d=Ab(a,"enum");b=M(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ma(d.name+"_"+b,function(){})}});a.values[c]=d;a[b]=d},C:function(a,b,c){c=Qa(c);b=M(b);L(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},
argPackAdvance:8,readValueFromPointer:Bb(b,c),ua:null})},m:function(a,b,c,d,e){b=M(b);-1===e&&(e=4294967295);e=Qa(c);var f=h=>h;if(0===d){var l=32-8*c;f=h=>h<<l>>>l}c=b.includes("unsigned")?function(h,m){return m>>>0}:function(h,m){return m};L(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:Cb(b,e,0!==d),ua:null})},i:function(a,b,c){function d(f){f>>=2;var l=F;return new e(ma,l[f+1],l[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,
Float64Array][b];c=M(c);L(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{ib:!0})},D:function(a,b){b=M(b);var c="std::string"===b;L(a,{name:b,fromWireType:function(d){var e=F[d>>2],f=d+4;if(c)for(var l=f,h=0;h<=e;++h){var m=f+h;if(h==e||0==C[m]){l=l?z(C,l,m-l):"";if(void 0===n)var n=l;else n+=String.fromCharCode(0),n+=l;l=m+1}}else{n=Array(e);for(h=0;h<e;++h)n[h]=String.fromCharCode(C[f+h]);n=n.join("")}V(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));
var f,l="string"==typeof e;l||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||P("Cannot pass non-string to std::string");c&&l?f=la(e):f=e.length;var h=Yb(4+f+1),m=h+4;F[h>>2]=f;if(c&&l)ka(e,C,m,f+1);else if(l)for(l=0;l<f;++l){var n=e.charCodeAt(l);255<n&&(V(m),P("String has UTF-16 code units that do not fit in 8 bits"));C[m+l]=n}else for(l=0;l<f;++l)C[m+l]=e[l];null!==d&&d.push(V,h);return h},argPackAdvance:8,readValueFromPointer:Ja,ua:function(d){V(d)}})},y:function(a,
b,c){c=M(c);if(2===b){var d=Eb;var e=Fb;var f=Gb;var l=()=>na;var h=1}else 4===b&&(d=Hb,e=Ib,f=Jb,l=()=>F,h=2);L(a,{name:c,fromWireType:function(m){for(var n=F[m>>2],p=l(),t,u=m+4,k=0;k<=n;++k){var r=m+4+k*b;if(k==n||0==p[r>>h])u=d(u,r-u),void 0===t?t=u:(t+=String.fromCharCode(0),t+=u),u=r+b}V(m);return t},toWireType:function(m,n){"string"!=typeof n&&P("Cannot pass non-string to C++ string type "+c);var p=f(n),t=Yb(4+p+b);F[t>>2]=p>>h;e(n,t+4,p+b);null!==m&&m.push(V,t);return t},argPackAdvance:8,
readValueFromPointer:Ja,ua:function(m){V(m)}})},G:function(a,b,c,d,e,f){Ha[a]={name:M(b),Pa:U(c,d),ya:U(e,f),Va:[]}},r:function(a,b,c,d,e,f,l,h,m,n){Ha[a].Va.push({ab:M(b),gb:c,eb:U(d,e),fb:f,pb:l,ob:U(h,m),qb:n})},W:function(a,b){b=M(b);L(a,{jb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},j:function(a,b,c){a=X(a);b=Ab(b,"emval::as");var d=[],e=S(d);F[c>>2]=e;return b.toWireType(d,a)},s:function(a,b,c,d){a=X(a);c=Kb(b,c);for(var e=Array(b),f=0;f<b;++f){var l=c[f];
e[f]=l.readValueFromPointer(d);d+=l.argPackAdvance}a=a.apply(void 0,e);return S(a)},v:function(a,b,c,d,e){a=Nb[a];b=X(b);c=Mb(c);var f=[];F[d>>2]=S(f);return a(b,c,f,e)},t:function(a,b,c,d){a=Nb[a];b=X(b);c=Mb(c);a(b,c,null,d)},a:yb,d:function(a,b){a=X(a);b=X(b);return a==b},o:function(a){if(0===a)return S(Ob());a=Mb(a);return S(Ob()[a])},n:function(a,b){var c=Kb(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(p){return p.name}).join("_")+"$";var e=Qb[b];if(void 0!==e)return e;e=["retType"];for(var f=
[d],l="",h=0;h<a-1;++h)l+=(0!==h?", ":"")+"arg"+h,e.push("argType"+h),f.push(c[1+h]);var m="return function "+La("methodCaller_"+b)+"(handle, name, destructors, args) {\n",n=0;for(h=0;h<a-1;++h)m+="    var arg"+h+" = argType"+h+".readValueFromPointer(args"+(n?"+"+n:"")+");\n",n+=c[h+1].argPackAdvance;m+="    var rv = handle[name]("+l+");\n";for(h=0;h<a-1;++h)c[h+1].deleteObject&&(m+="    argType"+h+".deleteObject(arg"+h+");\n");d.jb||(m+="    return retType.toWireType(destructors, rv);\n");e.push(m+
"};\n");a=ub(e).apply(null,f);e=Pb(a);return Qb[b]=e},f:function(a,b){a=X(a);b=X(b);return S(a[b])},c:function(a){4<a&&(W[a].Qa+=1)},p:function(a,b,c,d){a=X(a);var e=Sb[b];e||(e=Rb(b),Sb[b]=e);return e(a,c,d)},e:function(a){return S(Mb(a))},h:function(a){var b=X(a);Ia(b);yb(a)},q:function(a,b,c){a=X(a);b=X(b);c=X(c);a[b]=c},g:function(a,b){a=Ab(a,"_emval_take_value");a=a.readValueFromPointer(b);return S(a)},Q:function(a,b){a=new Date(1E3*(F[a>>2]+4294967296*E[a+4>>2]));E[b>>2]=a.getSeconds();E[b+
4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();E[b+28>>2]=Wb(a)|0;E[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();E[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},R:function(a){var b=new Date(E[a+20>>2]+1900,E[a+16>>2],E[a+12>>2],E[a+8>>2],E[a+4>>2],E[a>>2],0),c=E[a+32>>2],d=b.getTimezoneOffset(),
e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),l=Math.min(f,e);0>c?E[a+32>>2]=Number(e!=f&&l==d):0<c!=(l==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?l:e)-d)));E[a+24>>2]=b.getDay();E[a+28>>2]=Wb(b)|0;E[a>>2]=b.getSeconds();E[a+4>>2]=b.getMinutes();E[a+8>>2]=b.getHours();E[a+12>>2]=b.getDate();E[a+16>>2]=b.getMonth();E[a+20>>2]=b.getYear();return b.getTime()/1E3|0},S:function(a,b,c){function d(m){return(m=m.toTimeString().match(/\(([A-Za-z ]+)\)$/))?
m[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),l=new Date(e,6,1);e=f.getTimezoneOffset();var h=l.getTimezoneOffset();F[a>>2]=60*Math.max(e,h);E[b>>2]=Number(e!=h);a=d(f);b=d(l);a=Xb(a);b=Xb(b);h<e?(F[c>>2]=a,F[c+4>>2]=b):(F[c>>2]=b,F[c+4>>2]=a)},b:function(){x("")},Y:function(a,b,c){Zb.length=0;var d;for(c>>=2;d=C[b++];)c+=105!=d&c,Zb.push(105==d?E[c]:pa[c++>>1]),++c;return Ea[a].apply(null,Zb)},z:function(a,b,c,d,e,f){b=b?z(C,b):"";a=Ac[a];var l=-1;e&&(l=a.Ha.length,a.Ha.push({Na:ob(e),
Ma:f}),a.Sa++);b={funcName:b,callbackId:l,data:c?new Uint8Array(C.subarray(c,c+d)):0};c?a.worker.postMessage(b,[b.data.buffer]):a.worker.postMessage(b)},T:function(a){a=a?z(C,a):"";var b=Ac.length;a={worker:new Worker(a),Ha:[],Sa:0,buffer:0,bufferSize:0};a.worker.onmessage=function(c){if(!y){var d=Ac[b];if(d){var e=c.data.callbackId,f=d.Ha[e];if(f)if(c.data.finalResponse&&(d.Sa--,d.Ha[e]=null),c=c.data.data){c.byteLength||(c=new Uint8Array(c));if(!d.buffer||d.bufferSize<c.length)d.buffer&&V(d.buffer),
d.bufferSize=c.length,d.buffer=Yb(c.length);C.set(c,d.buffer);f.Na(d.buffer,c.length,f.Ma)}else f.Na(0,0,f.Ma)}}};Ac.push(a);return b},B:function(){return Date.now()},A:function(a){var b=Ac[a];b.worker.terminate();b.buffer&&V(b.buffer);Ac[a]=null},P:function(a,b,c){C.copyWithin(a,b,b+c)},_:function(){Y=null;Z++},L:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);e=e.min.call(e,2147483648,d+(65536-
d%65536)%65536);a:{try{ia.grow(e-ma.byteLength+65535>>>16);qa();var f=1;break a}catch(l){}f=void 0}if(f)return!0}return!1},Z:function(){wc()},X:function(a,b,c){a=ob(a);kc(a,b,c)},E:function(a,b){if(cd)throw"already responded with final response!";cd=!0;b={callbackId:dd,finalResponse:!0,data:a?new Uint8Array(C.subarray(a,a+b)):0};a?postMessage(b,[b.data.buffer]):postMessage(b)},N:function(a,b){var c=0;Sc().forEach(function(d,e){var f=b+c;e=F[a+4*e>>2]=f;for(f=0;f<d.length;++f)B[e++>>0]=d.charCodeAt(f);
B[e>>0]=0;c+=d.length+1});return 0},O:function(a,b){var c=Sc();F[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});F[b>>2]=d;return 0},M:function(a,b,c,d){for(var e=0,f=0;f<c;f++){var l=F[b>>2],h=F[b+4>>2];b+=8;for(var m=0;m<h;m++){var n=C[l+m],p=Uc[a];0===n||10===n?((1===a?fa:v)(z(p,0)),p.length=0):p.push(n)}e+=h}F[d>>2]=e;return 0},J:Wc,K:function(a,b,c,d){return $c(a,b,c,d)}};
(function(){function a(e){g.asm=e.exports;ia=g.asm.$;qa();ra=g.asm.ha;ta.unshift(g.asm.aa);G--;g.monitorRunDependencies&&g.monitorRunDependencies(G);0==G&&(null!==ya&&(clearInterval(ya),ya=null),za&&(e=za,za=null,e()))}function b(e){a(e.instance)}function c(e){return Da().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){v("failed to asynchronously prepare wasm: "+f);x(f)})}var d={a:ed};G++;g.monitorRunDependencies&&g.monitorRunDependencies(G);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(e){return v("Module.instantiateWasm callback failed with error: "+e),!1}(function(){return ha||"function"!=typeof WebAssembly.instantiateStreaming||Aa()||"function"!=typeof fetch?c(b):fetch(H,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){v("wasm streaming compile failed: "+f);v("falling back to ArrayBuffer instantiation");return c(b)})})})();return{}})();
g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.aa).apply(null,arguments)};var Yb=g._malloc=function(){return(Yb=g._malloc=g.asm.ba).apply(null,arguments)},V=g._free=function(){return(V=g._free=g.asm.ca).apply(null,arguments)};g._main=function(){return(g._main=g.asm.da).apply(null,arguments)};g._pushData=function(){return(g._pushData=g.asm.ea).apply(null,arguments)};var sb=g.___getTypeName=function(){return(sb=g.___getTypeName=g.asm.fa).apply(null,arguments)};
g.__embind_initialize_bindings=function(){return(g.__embind_initialize_bindings=g.asm.ga).apply(null,arguments)};var fd=g.stackAlloc=function(){return(fd=g.stackAlloc=g.asm.ia).apply(null,arguments)};g.dynCall_viijj=function(){return(g.dynCall_viijj=g.asm.ja).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.ka).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.la).apply(null,arguments)};
g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.ma).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.na).apply(null,arguments)};g.out=fa;var gd;za=function hd(){gd||jd();gd||(za=hd)};function kd(a){var b=g._main;a=a||[];a.unshift(ca);var c=a.length,d=fd(4*(c+1)),e=d>>2;a.forEach(l=>{var h=E,m=e++,n=la(l)+1,p=fd(n);ka(l,B,p,n);h[m]=p});E[e]=0;try{var f=b(c,d);ic(f)}catch(l){jc(l)}}
function jd(){function a(){if(!gd&&(gd=!0,g.calledRun=!0,!y)){wa=!0;Ga(ta);Ga(ua);if(g.onRuntimeInitialized)g.onRuntimeInitialized();ld&&kd(b);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();va.unshift(c)}Ga(va)}}var b=b||ba;if(!(0<G)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)xa();Ga(sa);0<G||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},
1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var ld=!0;g.noInitialRun&&(ld=!1);jd();var cd=!1,dd=-1;
(function(){function a(){if(c&&wa){var f=c;c=null;f.forEach(function(l){onmessage(l)})}}function b(){a();c&&setTimeout(b,100)}var c=null,d=0,e=0;onmessage=f=>{if(wa){a();var l=g["_"+f.data.funcName];if(!l)throw"invalid worker function to call: "+f.data.funcName;var h=f.data.data;if(h){h.byteLength||(h=new Uint8Array(h));if(!d||e<h.length)d&&V(d),e=h.length,d=Yb(h.length);C.set(h,d)}cd=!1;dd=f.data.callbackId;h?l(d,h.length):l(0,0)}else c||(c=[],setTimeout(b,100)),c.push(f)}})();
