
var TWASMModule = (() => {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  
  return (
function(TWASMModule) {
  TWASMModule = TWASMModule || {};


var g;g||(g=typeof TWASMModule !== 'undefined' ? TWASMModule : {});var aa,ba;g.ready=new Promise(function(a,b){aa=a;ba=b});var ca=Object.assign({},g),da=[],ea="./this.program",fa=(a,b)=>{throw b;},q="";"undefined"!=typeof document&&document.currentScript&&(q=document.currentScript.src);_scriptDir&&(q=_scriptDir);0!==q.indexOf("blob:")?q=q.substr(0,q.replace(/[?#].*/,"").lastIndexOf("/")+1):q="";var ha=g.print||console.log.bind(console),v=g.printErr||console.warn.bind(console);
Object.assign(g,ca);ca=null;g.arguments&&(da=g.arguments);g.thisProgram&&(ea=g.thisProgram);g.quit&&(fa=g.quit);var ia;g.wasmBinary&&(ia=g.wasmBinary);var noExitRuntime=g.noExitRuntime||!0;"object"!=typeof WebAssembly&&x("no native wasm support detected");var ja,y=!1,ka="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function z(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&ka)return ka.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var l=a[b++]&63;e=224==(e&240)?(e&15)<<12|f<<6|l:(e&7)<<18|f<<12|l<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}
function la(a,b,c,d){if(0<d){d=c+d-1;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}if(127>=f){if(c>=d)break;b[c++]=f}else{if(2047>=f){if(c+1>=d)break;b[c++]=192|f>>6}else{if(65535>=f){if(c+2>=d)break;b[c++]=224|f>>12}else{if(c+3>=d)break;b[c++]=240|f>>18;b[c++]=128|f>>12&63}b[c++]=128|f>>6&63}b[c++]=128|f&63}}b[c]=0}}
function ma(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}var na,B,C,D,oa,E,F,pa,qa;function ra(){var a=ja.buffer;na=a;g.HEAP8=B=new Int8Array(a);g.HEAP16=D=new Int16Array(a);g.HEAP32=E=new Int32Array(a);g.HEAPU8=C=new Uint8Array(a);g.HEAPU16=oa=new Uint16Array(a);g.HEAPU32=F=new Uint32Array(a);g.HEAPF32=pa=new Float32Array(a);g.HEAPF64=qa=new Float64Array(a)}var sa,ta=[],ua=[],va=[],wa=[];
function xa(){var a=g.preRun.shift();ta.unshift(a)}var G=0,ya=null,za=null;function x(a){if(g.onAbort)g.onAbort(a);a="Aborted("+a+")";v(a);y=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ba(a);throw a;}function Aa(){return H.startsWith("data:application/octet-stream;base64,")}var H;H="thing.wasm.wasm";if(!Aa()){var Ba=H;H=g.locateFile?g.locateFile(Ba,q):q+Ba}
function Ca(){var a=H;try{if(a==H&&ia)return new Uint8Array(ia);throw"both async and sync fetching of the wasm failed";}catch(b){x(b)}}function Da(){return ia||"function"!=typeof fetch?Promise.resolve().then(function(){return Ca()}):fetch(H,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+H+"'";return a.arrayBuffer()}).catch(function(){return Ca()})}
var Ea={56576:()=>{function a(b){try{return decodeURIComponent(escape(b))}catch(c){return String.fromCharCode(65533)}}window.decodeBufferToString=function(b){var c=b.length,d="",e="";c=Math.min(b.length,c||Infinity);for(var f=0;f<c;f++)127>=b[f]?(d+=a(e)+String.fromCharCode(b[f]),e=""):e+="%"+b[f].toString(16);return d+a(e)}}};function Fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Ga(a){for(;0<a.length;)a.shift()(g)}var Ha={};
function Ia(a){for(;a.length;){var b=a.pop();a.pop()(b)}}function Ja(a){return this.fromWireType(E[a>>2])}var I={},J={},Ka={};function La(a){if(void 0===a)return"_unknown";a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?"_"+a:a}function Ma(a,b){a=La(a);return(new Function("body","return function "+a+'() {\n    "use strict";    return body.apply(this, arguments);\n};\n'))(b)}
function Na(a){var b=Error,c=Ma(a,function(d){this.name=a;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(b.prototype);c.prototype.constructor=c;c.prototype.toString=function(){return void 0===this.message?this.name:this.name+": "+this.message};return c}var Oa=void 0;function Pa(a){throw new Oa(a);}
function K(a,b,c){function d(k){k=c(k);k.length!==a.length&&Pa("Mismatched type converter count");for(var m=0;m<a.length;++m)L(a[m],k[m])}a.forEach(function(k){Ka[k]=b});var e=Array(b.length),f=[],l=0;b.forEach((k,m)=>{J.hasOwnProperty(k)?e[m]=J[k]:(f.push(k),I.hasOwnProperty(k)||(I[k]=[]),I[k].push(()=>{e[m]=J[k];++l;l===f.length&&d(e)}))});0===f.length&&d(e)}
function Qa(a){switch(a){case 1:return 0;case 2:return 1;case 4:return 2;case 8:return 3;default:throw new TypeError("Unknown type size: "+a);}}var Ra=void 0;function M(a){for(var b="";C[a];)b+=Ra[C[a++]];return b}var N=void 0;function P(a){throw new N(a);}
function L(a,b,c={}){if(!("argPackAdvance"in b))throw new TypeError("registerType registeredInstance requires argPackAdvance");var d=b.name;a||P('type "'+d+'" must have a positive integer typeid pointer');if(J.hasOwnProperty(a)){if(c.gb)return;P("Cannot register type '"+d+"' twice")}J[a]=b;delete Ka[a];I.hasOwnProperty(a)&&(b=I[a],delete I[a],b.forEach(e=>e()))}function Sa(a){P(a.ma.pa.na.name+" instance already deleted")}var Ta=!1;function Ua(){}
function Va(a){--a.count.value;0===a.count.value&&(a.ra?a.ta.wa(a.ra):a.pa.na.wa(a.oa))}function Wa(a,b,c){if(b===c)return a;if(void 0===c.ua)return null;a=Wa(a,b,c.ua);return null===a?null:c.Ya(a)}var Xa={},Ya=[];function Za(){for(;Ya.length;){var a=Ya.pop();a.ma.Ba=!1;a["delete"]()}}var $a=void 0,ab={};function bb(a,b){for(void 0===b&&P("ptr should not be undefined");a.ua;)b=a.Ea(b),a=a.ua;return ab[b]}
function cb(a,b){b.pa&&b.oa||Pa("makeClassHandle requires ptr and ptrType");!!b.ta!==!!b.ra&&Pa("Both smartPtrType and smartPtr must be specified");b.count={value:1};return db(Object.create(a,{ma:{value:b}}))}function db(a){if("undefined"===typeof FinalizationRegistry)return db=b=>b,a;Ta=new FinalizationRegistry(b=>{Va(b.ma)});db=b=>{var c=b.ma;c.ra&&Ta.register(b,{ma:c},b);return b};Ua=b=>{Ta.unregister(b)};return db(a)}function Q(){}
function eb(a,b,c){if(void 0===a[b].qa){var d=a[b];a[b]=function(){a[b].qa.hasOwnProperty(arguments.length)||P("Function '"+c+"' called with an invalid number of arguments ("+arguments.length+") - expects one of ("+a[b].qa+")!");return a[b].qa[arguments.length].apply(this,arguments)};a[b].qa=[];a[b].qa[d.Aa]=d}}
function fb(a,b){g.hasOwnProperty(a)?(P("Cannot register public name '"+a+"' twice"),eb(g,a,a),g.hasOwnProperty(void 0)&&P("Cannot register multiple overloads of a function with the same number of arguments (undefined)!"),g[a].qa[void 0]=b):g[a]=b}function gb(a,b,c,d,e,f,l,k){this.name=a;this.constructor=b;this.Ca=c;this.wa=d;this.ua=e;this.$a=f;this.Ea=l;this.Ya=k;this.jb=[]}
function hb(a,b,c){for(;b!==c;)b.Ea||P("Expected null or instance of "+c.name+", got an instance of "+b.name),a=b.Ea(a),b=b.ua;return a}function ib(a,b){if(null===b)return this.Ma&&P("null is not a valid "+this.name),0;b.ma||P('Cannot pass "'+jb(b)+'" as a '+this.name);b.ma.oa||P("Cannot pass deleted object as a pointer of type "+this.name);return hb(b.ma.oa,b.ma.pa.na,this.na)}
function kb(a,b){if(null===b){this.Ma&&P("null is not a valid "+this.name);if(this.Ha){var c=this.Na();null!==a&&a.push(this.wa,c);return c}return 0}b.ma||P('Cannot pass "'+jb(b)+'" as a '+this.name);b.ma.oa||P("Cannot pass deleted object as a pointer of type "+this.name);!this.Ga&&b.ma.pa.Ga&&P("Cannot convert argument of type "+(b.ma.ta?b.ma.ta.name:b.ma.pa.name)+" to parameter type "+this.name);c=hb(b.ma.oa,b.ma.pa.na,this.na);if(this.Ha)switch(void 0===b.ma.ra&&P("Passing raw pointer to smart pointer is illegal"),
this.pb){case 0:b.ma.ta===this?c=b.ma.ra:P("Cannot convert argument of type "+(b.ma.ta?b.ma.ta.name:b.ma.pa.name)+" to parameter type "+this.name);break;case 1:c=b.ma.ra;break;case 2:if(b.ma.ta===this)c=b.ma.ra;else{var d=b.clone();c=this.lb(c,S(function(){d["delete"]()}));null!==a&&a.push(this.wa,c)}break;default:P("Unsupporting sharing policy")}return c}
function lb(a,b){if(null===b)return this.Ma&&P("null is not a valid "+this.name),0;b.ma||P('Cannot pass "'+jb(b)+'" as a '+this.name);b.ma.oa||P("Cannot pass deleted object as a pointer of type "+this.name);b.ma.pa.Ga&&P("Cannot convert argument of type "+b.ma.pa.name+" to parameter type "+this.name);return hb(b.ma.oa,b.ma.pa.na,this.na)}
function T(a,b,c,d){this.name=a;this.na=b;this.Ma=c;this.Ga=d;this.Ha=!1;this.wa=this.lb=this.Na=this.Wa=this.pb=this.ib=void 0;void 0!==b.ua?this.toWireType=kb:(this.toWireType=d?ib:lb,this.sa=null)}function mb(a,b){g.hasOwnProperty(a)||Pa("Replacing nonexistant public symbol");g[a]=b;g[a].Aa=void 0}var nb=[];function ob(a){var b=nb[a];b||(a>=nb.length&&(nb.length=a+1),nb[a]=b=sa.get(a));return b}
function pb(a,b){var c=[];return function(){c.length=0;Object.assign(c,arguments);if(a.includes("j")){var d=g["dynCall_"+a];d=c&&c.length?d.apply(null,[b].concat(c)):d.call(null,b)}else d=ob(b).apply(null,c);return d}}function U(a,b){a=M(a);var c=a.includes("j")?pb(a,b):ob(b);"function"!=typeof c&&P("unknown function pointer with signature "+a+": "+b);return c}var qb=void 0;function rb(a){a=sb(a);var b=M(a);V(a);return b}
function tb(a,b){function c(f){e[f]||J[f]||(Ka[f]?Ka[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new qb(a+": "+d.map(rb).join([", "]));}function ub(a){var b=Function;if(!(b instanceof Function))throw new TypeError("new_ called with constructor type "+typeof b+" which is not a function");var c=Ma(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
function vb(a,b,c,d,e){var f=b.length;2>f&&P("argTypes array size mismatch! Must at least get return value and 'this' types!");var l=null!==b[1]&&null!==c,k=!1;for(c=1;c<b.length;++c)if(null!==b[c]&&void 0===b[c].sa){k=!0;break}var m="void"!==b[0].name,n="",p="";for(c=0;c<f-2;++c)n+=(0!==c?", ":"")+"arg"+c,p+=(0!==c?", ":"")+"arg"+c+"Wired";a="return function "+La(a)+"("+n+") {\nif (arguments.length !== "+(f-2)+") {\nthrowBindingError('function "+a+" called with ' + arguments.length + ' arguments, expected "+
(f-2)+" args!');\n}\n";k&&(a+="var destructors = [];\n");var t=k?"destructors":"null";n="throwBindingError invoker fn runDestructors retType classParam".split(" ");d=[P,d,e,Ia,b[0],b[1]];l&&(a+="var thisWired = classParam.toWireType("+t+", this);\n");for(c=0;c<f-2;++c)a+="var arg"+c+"Wired = argType"+c+".toWireType("+t+", arg"+c+"); // "+b[c+2].name+"\n",n.push("argType"+c),d.push(b[c+2]);l&&(p="thisWired"+(0<p.length?", ":"")+p);a+=(m?"var rv = ":"")+"invoker(fn"+(0<p.length?", ":"")+p+");\n";if(k)a+=
"runDestructors(destructors);\n";else for(c=l?1:2;c<b.length;++c)f=1===c?"thisWired":"arg"+(c-2)+"Wired",null!==b[c].sa&&(a+=f+"_dtor("+f+"); // "+b[c].name+"\n",n.push(f+"_dtor"),d.push(b[c].sa));m&&(a+="var ret = retType.fromWireType(rv);\nreturn ret;\n");n.push(a+"}\n");return ub(n).apply(null,d)}function wb(a,b){for(var c=[],d=0;d<a;d++)c.push(F[b+4*d>>2]);return c}var xb=[],W=[{},{value:void 0},{value:null},{value:!0},{value:!1}];function yb(a){4<a&&0===--W[a].Oa&&(W[a]=void 0,xb.push(a))}
var X=a=>{a||P("Cannot use deleted val. handle = "+a);return W[a].value},S=a=>{switch(a){case void 0:return 1;case null:return 2;case !0:return 3;case !1:return 4;default:var b=xb.length?xb.pop():W.length;W[b]={Oa:1,value:a};return b}};
function zb(a,b,c){switch(b){case 0:return function(d){return this.fromWireType((c?B:C)[d])};case 1:return function(d){return this.fromWireType((c?D:oa)[d>>1])};case 2:return function(d){return this.fromWireType((c?E:F)[d>>2])};default:throw new TypeError("Unknown integer type: "+a);}}function Ab(a,b){var c=J[a];void 0===c&&P(b+" has unknown type "+rb(a));return c}function jb(a){if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a}
function Bb(a,b){switch(b){case 2:return function(c){return this.fromWireType(pa[c>>2])};case 3:return function(c){return this.fromWireType(qa[c>>3])};default:throw new TypeError("Unknown float type: "+a);}}
function Cb(a,b,c){switch(b){case 0:return c?function(d){return B[d]}:function(d){return C[d]};case 1:return c?function(d){return D[d>>1]}:function(d){return oa[d>>1]};case 2:return c?function(d){return E[d>>2]}:function(d){return F[d>>2]};default:throw new TypeError("Unknown integer type: "+a);}}var Db="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0;
function Eb(a,b){var c=a>>1;for(var d=c+b/2;!(c>=d)&&oa[c];)++c;c<<=1;if(32<c-a&&Db)return Db.decode(C.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=D[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c}function Fb(a,b,c){void 0===c&&(c=2147483647);if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d}function Gb(a){return 2*a.length}
function Hb(a,b){for(var c=0,d="";!(c>=b/4);){var e=E[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d}function Ib(a,b,c){void 0===c&&(c=2147483647);if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.charCodeAt(e);if(55296<=f&&57343>=f){var l=a.charCodeAt(++e);f=65536+((f&1023)<<10)|l&1023}E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d}
function Jb(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b}function Kb(a,b){for(var c=Array(a),d=0;d<a;++d)c[d]=Ab(F[b+4*d>>2],"parameter "+d);return c}var Lb={};function Mb(a){var b=Lb[a];return void 0===b?M(a):b}var Nb=[];function Ob(){return"object"==typeof globalThis?globalThis:Function("return this")()}function Pb(a){var b=Nb.length;Nb.push(a);return b}var Qb=[];
function Rb(a){for(var b="",c=0;c<a;++c)b+=(0!==c?", ":"")+"arg"+c;var d="return function emval_allocator_"+a+"(constructor, argTypes, args) {\n  var HEAPU32 = getMemory();\n";for(c=0;c<a;++c)d+="var argType"+c+" = requireRegisteredType(HEAPU32[((argTypes)>>2)], 'parameter "+c+"');\nvar arg"+c+" = argType"+c+".readValueFromPointer(args);\nargs += argType"+c+"['argPackAdvance'];\nargTypes += 4;\n";return(new Function("requireRegisteredType","Module","valueToHandle","getMemory",d+("var obj = new constructor("+
b+");\nreturn valueToHandle(obj);\n}\n")))(Ab,g,S,()=>F)}var Sb={};function Tb(a){return 0===a%4&&(0!==a%100||0===a%400)}var Ub=[0,31,60,91,121,152,182,213,244,274,305,335],Vb=[0,31,59,90,120,151,181,212,243,273,304,334];function Wb(a){return(Tb(a.getFullYear())?Ub:Vb)[a.getMonth()]+a.getDate()-1}function Xb(a){var b=ma(a)+1,c=Yb(b);c&&la(a,B,c,b);return c}var Zb=[];
function $b(a,b){ac=a;bc=b;if(cc)if(dc||(dc=!0),0==a)Y=function(){var d=Math.max(0,ec+b-fc())|0;setTimeout(gc,d)};else if(1==a)Y=function(){hc(gc)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}Y=function(){setImmediate(gc)}}}var fc;fc=()=>performance.now();
function ic(a){if(!noExitRuntime){if(g.onExit)g.onExit(a);y=!0}fa(a,new Fa(a))}function jc(a){a instanceof Fa||"unwind"==a||fa(1,a)}
function kc(a,b,c,d,e){!cc||x("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");cc=a;lc=d;var f=Z;dc=!1;gc=function(){if(!y)if(0<mc.length){var l=Date.now(),k=mc.shift();k.La(k.Ka);if(nc){var m=nc,n=0==m%1?m-1:Math.floor(m);nc=k.wb?n:(8*m+(n+.5))/9}ha('main loop blocker "'+k.name+'" took '+(Date.now()-l)+" ms");g.setStatus&&(l=g.statusMessage||"Please wait...",
k=nc,m=oc.yb,k?k<m?g.setStatus(l+" ("+(m-k)+"/"+m+")"):g.setStatus(l):g.setStatus(""));f<Z||setTimeout(gc,0)}else f<Z||(pc=pc+1|0,1==ac&&1<bc&&0!=pc%bc?Y():(0==ac&&(ec=fc()),y||g.preMainLoop&&!1===g.preMainLoop()||(sc(a),g.postMainLoop&&g.postMainLoop()),f<Z||("object"==typeof SDL&&SDL.audio&&SDL.audio.kb&&SDL.audio.kb(),Y())))};e||(b&&0<b?$b(0,1E3/b):$b(1,1),Y());if(c)throw"unwind";}function sc(a){if(!y)try{a()}catch(b){jc(b)}}function tc(a){setTimeout(function(){sc(a)},1E4)}
function uc(a){vc||(vc={});vc[a]||(vc[a]=1,v(a))}var vc,dc=!1,Y=null,Z=0,cc=null,lc=0,ac=0,bc=0,pc=0,mc=[];function wc(){Z++;var a=ac,b=bc,c=cc;cc=null;kc(c,0,!1,lc,!0);$b(a,b);Y()}var oc={},ec,gc,nc,xc=!1,yc=!1,zc=[],Ac=[];
function Bc(){function a(){yc=document.pointerLockElement===g.canvas||document.mozPointerLockElement===g.canvas||document.webkitPointerLockElement===g.canvas||document.msPointerLockElement===g.canvas}g.preloadPlugins||(g.preloadPlugins=[]);if(!Cc){Cc=!0;try{Dc=!0}catch(c){Dc=!1,v("warning: no blob constructor, cannot create blobs with mimetypes")}Ec="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:Dc?null:v("warning: no BlobBuilder");Fc="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;g.Ua||"undefined"!=typeof Fc||(v("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),g.Ua=!0);g.preloadPlugins.push({canHandle:function(c){return!g.Ua&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,f){var l=null;if(Dc)try{l=new Blob([c],{type:Gc(d)}),l.size!==c.length&&(l=new Blob([(new Uint8Array(c)).buffer],{type:Gc(d)}))}catch(n){uc("Blob constructor present but fails: "+
n+"; falling back to blob builder")}l||(l=new Ec,l.append((new Uint8Array(c)).buffer),l=l.getBlob());var k=Fc.createObjectURL(l),m=new Image;m.onload=()=>{m.complete||x("Image "+d+" could not be decoded");var n=document.createElement("canvas");n.width=m.width;n.height=m.height;n.getContext("2d").drawImage(m,0,0);Fc.revokeObjectURL(k);e&&e(c)};m.onerror=()=>{ha("Image "+k+" could not be decoded");f&&f()};m.src=k}});g.preloadPlugins.push({canHandle:function(c){return!g.Bb&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,f){function l(){m||(m=!0,e&&e(c))}function k(){m||(m=!0,new Audio,f&&f())}var m=!1;if(Dc){try{var n=new Blob([c],{type:Gc(d)})}catch(t){return k()}n=Fc.createObjectURL(n);var p=new Audio;p.addEventListener("canplaythrough",()=>l(p),!1);p.onerror=function(){if(!m){v("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var t="",u=0,h=0,r=0;r<c.length;r++)for(u=u<<8|c[r],h+=8;6<=h;){var w=u>>h-6&63;h-=6;t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[w]}2==
h?(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&3)<<4],t+="=="):4==h&&(t+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(u&15)<<2],t+="=");p.src="data:audio/x-"+d.substr(-3)+";base64,"+t;l(p)}};p.src=n;tc(function(){l(p)})}else return k()}});var b=g.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),g.elementPointerLock&&b.addEventListener("click",c=>{!yc&&g.canvas.requestPointerLock&&(g.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function Hc(a,b,c,d){if(b&&g.Ra&&a==g.canvas)return g.Ra;var e;if(b){var f={antialias:!1,alpha:!1,zb:1};if(d)for(var l in d)f[l]=d[l];if("undefined"!=typeof GL&&(e=GL.xb(a,f)))var k=GL.getContext(e).vb}else k=a.getContext("2d");if(!k)return null;c&&(b||"undefined"==typeof GLctx||x("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),g.Ra=k,b&&GL.Ab(e),g.Db=b,zc.forEach(function(m){m()}),Bc());return k}var Ic=!1,Jc=void 0,Kc=void 0;
function Lc(a,b){function c(){xc=!1;var f=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===f?(d.exitFullscreen=Mc,Jc&&d.requestPointerLock(),xc=!0,Kc?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=F[SDL.screen>>2]|8388608),Nc(g.canvas),Oc()):Nc(d)):(f.parentNode.insertBefore(d,f),f.parentNode.removeChild(f),Kc?("undefined"!=typeof SDL&&(E[SDL.screen>>2]=F[SDL.screen>>2]&
-8388609),Nc(g.canvas),Oc()):Nc(d));if(g.onFullScreen)g.onFullScreen(xc);if(g.onFullscreen)g.onFullscreen(xc)}Jc=a;Kc=b;"undefined"==typeof Jc&&(Jc=!0);"undefined"==typeof Kc&&(Kc=!1);var d=g.canvas;Ic||(Ic=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Mc(){if(!xc)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||function(){}).apply(document,[]);return!0}var Pc=0;function hc(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Pc)Pc=b+1E3/60;else for(;b+2>=Pc;)Pc+=1E3/60;setTimeout(a,Math.max(Pc-b,0))}}
function Gc(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Qc=[];function Oc(){var a=g.canvas;Qc.forEach(function(b){b(a.width,a.height)})}
function Nc(a,b,c){b&&c?(a.ub=b,a.fb=c):(b=a.ub,c=a.fb);var d=b,e=c;g.forcedAspectRatio&&0<g.forcedAspectRatio&&(d/e<g.forcedAspectRatio?d=Math.round(e*g.forcedAspectRatio):e=Math.round(d/g.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var f=Math.min(screen.width/d,screen.height/e);d=Math.round(d*f);e=Math.round(e*
f)}Kc?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}var Cc,Dc,Ec,Fc,Rc={};
function Sc(){if(!Tc){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ea||"./this.program"},b;for(b in Rc)void 0===Rc[b]?delete a[b]:a[b]=Rc[b];var c=[];for(b in a)c.push(b+"="+a[b]);Tc=c}return Tc}var Tc,Uc=[null,[],[]];
function Vc(){if("object"==typeof crypto&&"function"==typeof crypto.getRandomValues){var a=new Uint8Array(1);return()=>{crypto.getRandomValues(a);return a[0]}}return()=>x("randomDevice")}function Wc(a,b){Wc.Va||(Wc.Va=Vc());for(var c=0;c<b;c++)B[a+c>>0]=Wc.Va();return 0}var Xc=[31,29,31,30,31,30,31,31,30,31,30,31],Yc=[31,28,31,30,31,30,31,31,30,31,30,31];function Zc(a){var b=Array(ma(a)+1);la(a,b,0,b.length);return b}
function $c(a,b,c,d){function e(h,r,w){for(h="number"==typeof h?h.toString():h||"";h.length<r;)h=w[0]+h;return h}function f(h,r){return e(h,r,"0")}function l(h,r){function w(R){return 0>R?-1:0<R?1:0}var A;0===(A=w(h.getFullYear()-r.getFullYear()))&&0===(A=w(h.getMonth()-r.getMonth()))&&(A=w(h.getDate()-r.getDate()));return A}function k(h){switch(h.getDay()){case 0:return new Date(h.getFullYear()-1,11,29);case 1:return h;case 2:return new Date(h.getFullYear(),0,3);case 3:return new Date(h.getFullYear(),
0,2);case 4:return new Date(h.getFullYear(),0,1);case 5:return new Date(h.getFullYear()-1,11,31);case 6:return new Date(h.getFullYear()-1,11,30)}}function m(h){var r=h.ya;for(h=new Date((new Date(h.za+1900,0,1)).getTime());0<r;){var w=h.getMonth(),A=(Tb(h.getFullYear())?Xc:Yc)[w];if(r>A-h.getDate())r-=A-h.getDate()+1,h.setDate(1),11>w?h.setMonth(w+1):(h.setMonth(0),h.setFullYear(h.getFullYear()+1));else{h.setDate(h.getDate()+r);break}}w=new Date(h.getFullYear()+1,0,4);r=k(new Date(h.getFullYear(),
0,4));w=k(w);return 0>=l(r,h)?0>=l(w,h)?h.getFullYear()+1:h.getFullYear():h.getFullYear()-1}var n=E[d+40>>2];d={sb:E[d>>2],rb:E[d+4>>2],Ia:E[d+8>>2],Pa:E[d+12>>2],Ja:E[d+16>>2],za:E[d+20>>2],va:E[d+24>>2],ya:E[d+28>>2],Cb:E[d+32>>2],qb:E[d+36>>2],tb:n?n?z(C,n):"":""};c=c?z(C,c):"";n={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y",
"%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var p in n)c=c.replace(new RegExp(p,"g"),n[p]);var t="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),u="January February March April May June July August September October November December".split(" ");n={"%a":function(h){return t[h.va].substring(0,3)},"%A":function(h){return t[h.va]},"%b":function(h){return u[h.Ja].substring(0,
3)},"%B":function(h){return u[h.Ja]},"%C":function(h){return f((h.za+1900)/100|0,2)},"%d":function(h){return f(h.Pa,2)},"%e":function(h){return e(h.Pa,2," ")},"%g":function(h){return m(h).toString().substring(2)},"%G":function(h){return m(h)},"%H":function(h){return f(h.Ia,2)},"%I":function(h){h=h.Ia;0==h?h=12:12<h&&(h-=12);return f(h,2)},"%j":function(h){for(var r=0,w=0;w<=h.Ja-1;r+=(Tb(h.za+1900)?Xc:Yc)[w++]);return f(h.Pa+r,3)},"%m":function(h){return f(h.Ja+1,2)},"%M":function(h){return f(h.rb,
2)},"%n":function(){return"\n"},"%p":function(h){return 0<=h.Ia&&12>h.Ia?"AM":"PM"},"%S":function(h){return f(h.sb,2)},"%t":function(){return"\t"},"%u":function(h){return h.va||7},"%U":function(h){return f(Math.floor((h.ya+7-h.va)/7),2)},"%V":function(h){var r=Math.floor((h.ya+7-(h.va+6)%7)/7);2>=(h.va+371-h.ya-2)%7&&r++;if(r)53==r&&(w=(h.va+371-h.ya)%7,4==w||3==w&&Tb(h.za)||(r=1));else{r=52;var w=(h.va+7-h.ya-1)%7;(4==w||5==w&&Tb(h.za%400-1))&&r++}return f(r,2)},"%w":function(h){return h.va},"%W":function(h){return f(Math.floor((h.ya+
7-(h.va+6)%7)/7),2)},"%y":function(h){return(h.za+1900).toString().substring(2)},"%Y":function(h){return h.za+1900},"%z":function(h){h=h.qb;var r=0<=h;h=Math.abs(h)/60;return(r?"+":"-")+String("0000"+(h/60*100+h%60)).slice(-4)},"%Z":function(h){return h.tb},"%%":function(){return"%"}};c=c.replace(/%%/g,"\x00\x00");for(p in n)c.includes(p)&&(c=c.replace(new RegExp(p,"g"),n[p](d)));c=c.replace(/\0\0/g,"%");p=Zc(c);if(p.length>b)return 0;B.set(p,a);return p.length-1}Oa=g.InternalError=Na("InternalError");
for(var ad=Array(256),bd=0;256>bd;++bd)ad[bd]=String.fromCharCode(bd);Ra=ad;N=g.BindingError=Na("BindingError");Q.prototype.isAliasOf=function(a){if(!(this instanceof Q&&a instanceof Q))return!1;var b=this.ma.pa.na,c=this.ma.oa,d=a.ma.pa.na;for(a=a.ma.oa;b.ua;)c=b.Ea(c),b=b.ua;for(;d.ua;)a=d.Ea(a),d=d.ua;return b===d&&c===a};
Q.prototype.clone=function(){this.ma.oa||Sa(this);if(this.ma.Da)return this.ma.count.value+=1,this;var a=db,b=Object,c=b.create,d=Object.getPrototypeOf(this),e=this.ma;a=a(c.call(b,d,{ma:{value:{count:e.count,Ba:e.Ba,Da:e.Da,oa:e.oa,pa:e.pa,ra:e.ra,ta:e.ta}}}));a.ma.count.value+=1;a.ma.Ba=!1;return a};Q.prototype["delete"]=function(){this.ma.oa||Sa(this);this.ma.Ba&&!this.ma.Da&&P("Object already scheduled for deletion");Ua(this);Va(this.ma);this.ma.Da||(this.ma.ra=void 0,this.ma.oa=void 0)};
Q.prototype.isDeleted=function(){return!this.ma.oa};Q.prototype.deleteLater=function(){this.ma.oa||Sa(this);this.ma.Ba&&!this.ma.Da&&P("Object already scheduled for deletion");Ya.push(this);1===Ya.length&&$a&&$a(Za);this.ma.Ba=!0;return this};g.getInheritedInstanceCount=function(){return Object.keys(ab).length};g.getLiveInheritedInstances=function(){var a=[],b;for(b in ab)ab.hasOwnProperty(b)&&a.push(ab[b]);return a};g.flushPendingDeletes=Za;g.setDelayFunction=function(a){$a=a;Ya.length&&$a&&$a(Za)};
T.prototype.ab=function(a){this.Wa&&(a=this.Wa(a));return a};T.prototype.Sa=function(a){this.wa&&this.wa(a)};T.prototype.argPackAdvance=8;T.prototype.readValueFromPointer=Ja;T.prototype.deleteObject=function(a){if(null!==a)a["delete"]()};
T.prototype.fromWireType=function(a){function b(){return this.Ha?cb(this.na.Ca,{pa:this.ib,oa:c,ta:this,ra:a}):cb(this.na.Ca,{pa:this,oa:a})}var c=this.ab(a);if(!c)return this.Sa(a),null;var d=bb(this.na,c);if(void 0!==d){if(0===d.ma.count.value)return d.ma.oa=c,d.ma.ra=a,d.clone();d=d.clone();this.Sa(a);return d}d=this.na.$a(c);d=Xa[d];if(!d)return b.call(this);d=this.Ga?d.Xa:d.pointerType;var e=Wa(c,this.na,d.na);return null===e?b.call(this):this.Ha?cb(d.na.Ca,{pa:d,oa:e,ta:this,ra:a}):cb(d.na.Ca,
{pa:d,oa:e})};qb=g.UnboundTypeError=Na("UnboundTypeError");g.count_emval_handles=function(){for(var a=0,b=5;b<W.length;++b)void 0!==W[b]&&++a;return a};g.get_first_emval=function(){for(var a=5;a<W.length;++a)if(void 0!==W[a])return W[a];return null};g.requestFullscreen=function(a,b){Lc(a,b)};g.requestAnimationFrame=function(a){hc(a)};g.setCanvasSize=function(a,b,c){Nc(g.canvas,a,b);c||Oc()};g.pauseMainLoop=function(){Y=null;Z++};g.resumeMainLoop=function(){wc()};
g.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};g.createContext=function(a,b,c,d){return Hc(a,b,c,d)};
var cd={E:function(a){var b=Ha[a];delete Ha[a];var c=b.Na,d=b.wa,e=b.Ta,f=e.map(l=>l.eb).concat(e.map(l=>l.nb));K([a],f,l=>{var k={};e.forEach((m,n)=>{var p=l[n],t=m.bb,u=m.cb,h=l[n+e.length],r=m.mb,w=m.ob;k[m.Za]={read:A=>p.fromWireType(t(u,A)),write:(A,R)=>{var O=[];r(w,A,h.toWireType(O,R));Ia(O)}}});return[{name:b.name,fromWireType:function(m){var n={},p;for(p in k)n[p]=k[p].read(m);d(m);return n},toWireType:function(m,n){for(var p in k)if(!(p in n))throw new TypeError('Missing field:  "'+p+'"');
var t=c();for(p in k)k[p].write(t,n[p]);null!==m&&m.push(d,t);return t},argPackAdvance:8,readValueFromPointer:Ja,sa:d}]})},H:function(){},U:function(a,b,c,d,e){var f=Qa(c);b=M(b);L(a,{name:b,fromWireType:function(l){return!!l},toWireType:function(l,k){return k?d:e},argPackAdvance:8,readValueFromPointer:function(l){if(1===c)var k=B;else if(2===c)k=D;else if(4===c)k=E;else throw new TypeError("Unknown boolean type size: "+b);return this.fromWireType(k[l>>f])},sa:null})},u:function(a,b,c,d,e,f,l,k,m,
n,p,t,u){p=M(p);f=U(e,f);k&&(k=U(l,k));n&&(n=U(m,n));u=U(t,u);var h=La(p);fb(h,function(){tb("Cannot construct "+p+" due to unbound types",[d])});K([a,b,c],d?[d]:[],function(r){r=r[0];if(d){var w=r.na;var A=w.Ca}else A=Q.prototype;r=Ma(h,function(){if(Object.getPrototypeOf(this)!==R)throw new N("Use 'new' to construct "+p);if(void 0===O.xa)throw new N(p+" has no accessible constructor");var qc=O.xa[arguments.length];if(void 0===qc)throw new N("Tried to invoke ctor of "+p+" with invalid number of parameters ("+
arguments.length+") - expected ("+Object.keys(O.xa).toString()+") parameters instead!");return qc.apply(this,arguments)});var R=Object.create(A,{constructor:{value:r}});r.prototype=R;var O=new gb(p,r,R,u,w,f,k,n);w=new T(p,O,!0,!1);A=new T(p+"*",O,!1,!1);var rc=new T(p+" const*",O,!1,!0);Xa[a]={pointerType:A,Xa:rc};mb(h,r);return[w,A,rc]})},k:function(a,b,c,d,e,f,l){var k=wb(c,d);b=M(b);f=U(e,f);K([],[a],function(m){function n(){tb("Cannot call "+p+" due to unbound types",k)}m=m[0];var p=m.name+"."+
b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var t=m.na.constructor;void 0===t[b]?(n.Aa=c-1,t[b]=n):(eb(t,b,p),t[b].qa[c-1]=n);K([],k,function(u){u=vb(p,[u[0],null].concat(u.slice(1)),null,f,l);void 0===t[b].qa?(u.Aa=c-1,t[b]=u):t[b].qa[c-1]=u;return[]});return[]})},w:function(a,b,c,d,e,f){0<b||x();var l=wb(b,c);e=U(d,e);K([],[a],function(k){k=k[0];var m="constructor "+k.name;void 0===k.na.xa&&(k.na.xa=[]);if(void 0!==k.na.xa[b-1])throw new N("Cannot register multiple constructors with identical number of parameters ("+
(b-1)+") for class '"+k.name+"'! Overload resolution is currently only performed using the parameter count, not actual type info!");k.na.xa[b-1]=()=>{tb("Cannot construct "+k.name+" due to unbound types",l)};K([],l,function(n){n.splice(1,0,null);k.na.xa[b-1]=vb(m,n,null,e,f);return[]});return[]})},l:function(a,b,c,d,e,f,l,k){var m=wb(c,d);b=M(b);f=U(e,f);K([],[a],function(n){function p(){tb("Cannot call "+t+" due to unbound types",m)}n=n[0];var t=n.name+"."+b;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);
k&&n.na.jb.push(b);var u=n.na.Ca,h=u[b];void 0===h||void 0===h.qa&&h.className!==n.name&&h.Aa===c-2?(p.Aa=c-2,p.className=n.name,u[b]=p):(eb(u,b,t),u[b].qa[c-2]=p);K([],m,function(r){r=vb(t,r,n,f,l);void 0===u[b].qa?(r.Aa=c-2,u[b]=r):u[b].qa[c-2]=r;return[]});return[]})},T:function(a,b){b=M(b);L(a,{name:b,fromWireType:function(c){var d=X(c);yb(c);return d},toWireType:function(c,d){return S(d)},argPackAdvance:8,readValueFromPointer:Ja,sa:null})},G:function(a,b,c,d){function e(){}c=Qa(c);b=M(b);e.values=
{};L(a,{name:b,constructor:e,fromWireType:function(f){return this.constructor.values[f]},toWireType:function(f,l){return l.value},argPackAdvance:8,readValueFromPointer:zb(b,c,d),sa:null});fb(b,e)},x:function(a,b,c){var d=Ab(a,"enum");b=M(b);a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Ma(d.name+"_"+b,function(){})}});a.values[c]=d;a[b]=d},C:function(a,b,c){c=Qa(c);b=M(b);L(a,{name:b,fromWireType:function(d){return d},toWireType:function(d,e){return e},
argPackAdvance:8,readValueFromPointer:Bb(b,c),sa:null})},m:function(a,b,c,d,e){b=M(b);-1===e&&(e=4294967295);e=Qa(c);var f=k=>k;if(0===d){var l=32-8*c;f=k=>k<<l>>>l}c=b.includes("unsigned")?function(k,m){return m>>>0}:function(k,m){return m};L(a,{name:b,fromWireType:f,toWireType:c,argPackAdvance:8,readValueFromPointer:Cb(b,e,0!==d),sa:null})},i:function(a,b,c){function d(f){f>>=2;var l=F;return new e(na,l[f+1],l[f])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,
Float64Array][b];c=M(c);L(a,{name:c,fromWireType:d,argPackAdvance:8,readValueFromPointer:d},{gb:!0})},D:function(a,b){b=M(b);var c="std::string"===b;L(a,{name:b,fromWireType:function(d){var e=F[d>>2],f=d+4;if(c)for(var l=f,k=0;k<=e;++k){var m=f+k;if(k==e||0==C[m]){l=l?z(C,l,m-l):"";if(void 0===n)var n=l;else n+=String.fromCharCode(0),n+=l;l=m+1}}else{n=Array(e);for(k=0;k<e;++k)n[k]=String.fromCharCode(C[f+k]);n=n.join("")}V(d);return n},toWireType:function(d,e){e instanceof ArrayBuffer&&(e=new Uint8Array(e));
var f,l="string"==typeof e;l||e instanceof Uint8Array||e instanceof Uint8ClampedArray||e instanceof Int8Array||P("Cannot pass non-string to std::string");c&&l?f=ma(e):f=e.length;var k=Yb(4+f+1),m=k+4;F[k>>2]=f;if(c&&l)la(e,C,m,f+1);else if(l)for(l=0;l<f;++l){var n=e.charCodeAt(l);255<n&&(V(m),P("String has UTF-16 code units that do not fit in 8 bits"));C[m+l]=n}else for(l=0;l<f;++l)C[m+l]=e[l];null!==d&&d.push(V,k);return k},argPackAdvance:8,readValueFromPointer:Ja,sa:function(d){V(d)}})},y:function(a,
b,c){c=M(c);if(2===b){var d=Eb;var e=Fb;var f=Gb;var l=()=>oa;var k=1}else 4===b&&(d=Hb,e=Ib,f=Jb,l=()=>F,k=2);L(a,{name:c,fromWireType:function(m){for(var n=F[m>>2],p=l(),t,u=m+4,h=0;h<=n;++h){var r=m+4+h*b;if(h==n||0==p[r>>k])u=d(u,r-u),void 0===t?t=u:(t+=String.fromCharCode(0),t+=u),u=r+b}V(m);return t},toWireType:function(m,n){"string"!=typeof n&&P("Cannot pass non-string to C++ string type "+c);var p=f(n),t=Yb(4+p+b);F[t>>2]=p>>k;e(n,t+4,p+b);null!==m&&m.push(V,t);return t},argPackAdvance:8,
readValueFromPointer:Ja,sa:function(m){V(m)}})},F:function(a,b,c,d,e,f){Ha[a]={name:M(b),Na:U(c,d),wa:U(e,f),Ta:[]}},r:function(a,b,c,d,e,f,l,k,m,n){Ha[a].Ta.push({Za:M(b),eb:c,bb:U(d,e),cb:f,nb:l,mb:U(k,m),ob:n})},V:function(a,b){b=M(b);L(a,{hb:!0,name:b,argPackAdvance:0,fromWireType:function(){},toWireType:function(){}})},j:function(a,b,c){a=X(a);b=Ab(b,"emval::as");var d=[],e=S(d);F[c>>2]=e;return b.toWireType(d,a)},s:function(a,b,c,d){a=X(a);c=Kb(b,c);for(var e=Array(b),f=0;f<b;++f){var l=c[f];
e[f]=l.readValueFromPointer(d);d+=l.argPackAdvance}a=a.apply(void 0,e);return S(a)},v:function(a,b,c,d,e){a=Nb[a];b=X(b);c=Mb(c);var f=[];F[d>>2]=S(f);return a(b,c,f,e)},t:function(a,b,c,d){a=Nb[a];b=X(b);c=Mb(c);a(b,c,null,d)},a:yb,d:function(a,b){a=X(a);b=X(b);return a==b},o:function(a){if(0===a)return S(Ob());a=Mb(a);return S(Ob()[a])},n:function(a,b){var c=Kb(a,b),d=c[0];b=d.name+"_$"+c.slice(1).map(function(p){return p.name}).join("_")+"$";var e=Qb[b];if(void 0!==e)return e;e=["retType"];for(var f=
[d],l="",k=0;k<a-1;++k)l+=(0!==k?", ":"")+"arg"+k,e.push("argType"+k),f.push(c[1+k]);var m="return function "+La("methodCaller_"+b)+"(handle, name, destructors, args) {\n",n=0;for(k=0;k<a-1;++k)m+="    var arg"+k+" = argType"+k+".readValueFromPointer(args"+(n?"+"+n:"")+");\n",n+=c[k+1].argPackAdvance;m+="    var rv = handle[name]("+l+");\n";for(k=0;k<a-1;++k)c[k+1].deleteObject&&(m+="    argType"+k+".deleteObject(arg"+k+");\n");d.hb||(m+="    return retType.toWireType(destructors, rv);\n");e.push(m+
"};\n");a=ub(e).apply(null,f);e=Pb(a);return Qb[b]=e},f:function(a,b){a=X(a);b=X(b);return S(a[b])},c:function(a){4<a&&(W[a].Oa+=1)},p:function(a,b,c,d){a=X(a);var e=Sb[b];e||(e=Rb(b),Sb[b]=e);return e(a,c,d)},e:function(a){return S(Mb(a))},h:function(a){var b=X(a);Ia(b);yb(a)},q:function(a,b,c){a=X(a);b=X(b);c=X(c);a[b]=c},g:function(a,b){a=Ab(a,"_emval_take_value");a=a.readValueFromPointer(b);return S(a)},P:function(a,b){a=new Date(1E3*(F[a>>2]+4294967296*E[a+4>>2]));E[b>>2]=a.getSeconds();E[b+
4>>2]=a.getMinutes();E[b+8>>2]=a.getHours();E[b+12>>2]=a.getDate();E[b+16>>2]=a.getMonth();E[b+20>>2]=a.getFullYear()-1900;E[b+24>>2]=a.getDay();E[b+28>>2]=Wb(a)|0;E[b+36>>2]=-(60*a.getTimezoneOffset());var c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset(),d=(new Date(a.getFullYear(),0,1)).getTimezoneOffset();E[b+32>>2]=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0},Q:function(a){var b=new Date(E[a+20>>2]+1900,E[a+16>>2],E[a+12>>2],E[a+8>>2],E[a+4>>2],E[a>>2],0),c=E[a+32>>2],d=b.getTimezoneOffset(),
e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),l=Math.min(f,e);0>c?E[a+32>>2]=Number(e!=f&&l==d):0<c!=(l==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?l:e)-d)));E[a+24>>2]=b.getDay();E[a+28>>2]=Wb(b)|0;E[a>>2]=b.getSeconds();E[a+4>>2]=b.getMinutes();E[a+8>>2]=b.getHours();E[a+12>>2]=b.getDate();E[a+16>>2]=b.getMonth();E[a+20>>2]=b.getYear();return b.getTime()/1E3|0},R:function(a,b,c){function d(m){return(m=m.toTimeString().match(/\(([A-Za-z ]+)\)$/))?
m[1]:"GMT"}var e=(new Date).getFullYear(),f=new Date(e,0,1),l=new Date(e,6,1);e=f.getTimezoneOffset();var k=l.getTimezoneOffset();F[a>>2]=60*Math.max(e,k);E[b>>2]=Number(e!=k);a=d(f);b=d(l);a=Xb(a);b=Xb(b);k<e?(F[c>>2]=a,F[c+4>>2]=b):(F[c>>2]=b,F[c+4>>2]=a)},b:function(){x("")},X:function(a,b,c){Zb.length=0;var d;for(c>>=2;d=C[b++];)c+=105!=d&c,Zb.push(105==d?E[c]:qa[c++>>1]),++c;return Ea[a].apply(null,Zb)},z:function(a,b,c,d,e,f){b=b?z(C,b):"";a=Ac[a];var l=-1;e&&(l=a.Fa.length,a.Fa.push({La:ob(e),
Ka:f}),a.Qa++);b={funcName:b,callbackId:l,data:c?new Uint8Array(C.subarray(c,c+d)):0};c?a.worker.postMessage(b,[b.data.buffer]):a.worker.postMessage(b)},S:function(a){a=a?z(C,a):"";var b=Ac.length;a={worker:new Worker(a),Fa:[],Qa:0,buffer:0,bufferSize:0};a.worker.onmessage=function(c){if(!y){var d=Ac[b];if(d){var e=c.data.callbackId,f=d.Fa[e];if(f)if(c.data.finalResponse&&(d.Qa--,d.Fa[e]=null),c=c.data.data){c.byteLength||(c=new Uint8Array(c));if(!d.buffer||d.bufferSize<c.length)d.buffer&&V(d.buffer),
d.bufferSize=c.length,d.buffer=Yb(c.length);C.set(c,d.buffer);f.La(d.buffer,c.length,f.Ka)}else f.La(0,0,f.Ka)}}};Ac.push(a);return b},B:function(){return Date.now()},A:function(a){var b=Ac[a];b.worker.terminate();b.buffer&&V(b.buffer);Ac[a]=null},O:function(a,b,c){C.copyWithin(a,b,b+c)},Z:function(){Y=null;Z++},K:function(a){var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);var e=Math;d=Math.max(a,d);e=e.min.call(e,2147483648,d+(65536-
d%65536)%65536);a:{try{ja.grow(e-na.byteLength+65535>>>16);ra();var f=1;break a}catch(l){}f=void 0}if(f)return!0}return!1},Y:function(){wc()},W:function(a,b,c){a=ob(a);kc(a,b,c)},M:function(a,b){var c=0;Sc().forEach(function(d,e){var f=b+c;e=F[a+4*e>>2]=f;for(f=0;f<d.length;++f)B[e++>>0]=d.charCodeAt(f);B[e>>0]=0;c+=d.length+1});return 0},N:function(a,b){var c=Sc();F[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});F[b>>2]=d;return 0},L:function(a,b,c,d){for(var e=0,f=0;f<c;f++){var l=
F[b>>2],k=F[b+4>>2];b+=8;for(var m=0;m<k;m++){var n=C[l+m],p=Uc[a];0===n||10===n?((1===a?ha:v)(z(p,0)),p.length=0):p.push(n)}e+=k}F[d>>2]=e;return 0},I:Wc,J:function(a,b,c,d){return $c(a,b,c,d)}};
(function(){function a(e){g.asm=e.exports;ja=g.asm._;ra();sa=g.asm.fa;ua.unshift(g.asm.$);G--;g.monitorRunDependencies&&g.monitorRunDependencies(G);0==G&&(null!==ya&&(clearInterval(ya),ya=null),za&&(e=za,za=null,e()))}function b(e){a(e.instance)}function c(e){return Da().then(function(f){return WebAssembly.instantiate(f,d)}).then(function(f){return f}).then(e,function(f){v("failed to asynchronously prepare wasm: "+f);x(f)})}var d={a:cd};G++;g.monitorRunDependencies&&g.monitorRunDependencies(G);if(g.instantiateWasm)try{return g.instantiateWasm(d,
a)}catch(e){v("Module.instantiateWasm callback failed with error: "+e),ba(e)}(function(){return ia||"function"!=typeof WebAssembly.instantiateStreaming||Aa()||"function"!=typeof fetch?c(b):fetch(H,{credentials:"same-origin"}).then(function(e){return WebAssembly.instantiateStreaming(e,d).then(b,function(f){v("wasm streaming compile failed: "+f);v("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
g.___wasm_call_ctors=function(){return(g.___wasm_call_ctors=g.asm.$).apply(null,arguments)};var Yb=g._malloc=function(){return(Yb=g._malloc=g.asm.aa).apply(null,arguments)},V=g._free=function(){return(V=g._free=g.asm.ba).apply(null,arguments)};g._main=function(){return(g._main=g.asm.ca).apply(null,arguments)};var sb=g.___getTypeName=function(){return(sb=g.___getTypeName=g.asm.da).apply(null,arguments)};
g.__embind_initialize_bindings=function(){return(g.__embind_initialize_bindings=g.asm.ea).apply(null,arguments)};var dd=g.stackAlloc=function(){return(dd=g.stackAlloc=g.asm.ga).apply(null,arguments)};g.dynCall_viijj=function(){return(g.dynCall_viijj=g.asm.ha).apply(null,arguments)};g.dynCall_jiji=function(){return(g.dynCall_jiji=g.asm.ia).apply(null,arguments)};g.dynCall_iiiiij=function(){return(g.dynCall_iiiiij=g.asm.ja).apply(null,arguments)};
g.dynCall_iiiiijj=function(){return(g.dynCall_iiiiijj=g.asm.ka).apply(null,arguments)};g.dynCall_iiiiiijj=function(){return(g.dynCall_iiiiiijj=g.asm.la).apply(null,arguments)};g.out=ha;var ed;za=function fd(){ed||gd();ed||(za=fd)};function hd(a){var b=g._main;a=a||[];a.unshift(ea);var c=a.length,d=dd(4*(c+1)),e=d>>2;a.forEach(l=>{var k=E,m=e++,n=ma(l)+1,p=dd(n);la(l,B,p,n);k[m]=p});E[e]=0;try{var f=b(c,d);ic(f)}catch(l){jc(l)}}
function gd(){function a(){if(!ed&&(ed=!0,g.calledRun=!0,!y)){Ga(ua);Ga(va);aa(g);if(g.onRuntimeInitialized)g.onRuntimeInitialized();jd&&hd(b);if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();wa.unshift(c)}Ga(wa)}}var b=b||da;if(!(0<G)){if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)xa();Ga(ta);0<G||(g.setStatus?(g.setStatus("Running..."),setTimeout(function(){setTimeout(function(){g.setStatus("")},
1);a()},1)):a())}}if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.pop()();var jd=!0;g.noInitialRun&&(jd=!1);gd();


  return TWASMModule.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = TWASMModule;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return TWASMModule; });
else if (typeof exports === 'object')
  exports["TWASMModule"] = TWASMModule;
